import type { College } from './types';

/**
 * After 12th Specialized Colleges Database - 2025 Addition  
 * Focus: Engineering Specializations, Medical/Allied Health, Commerce Specializations
 * 
 * All colleges include Google Maps URLs for easy navigation
 */

export const after12thSpecializedColleges2025: College[] = [
    // ==================== ENGINEERING SPECIALIZATIONS ====================

    // Aerospace Engineering
    {
        id: 'iit-bombay-aero',
        name: 'Indian Institute of Technology Bombay - Aerospace Engineering',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.Tech Aerospace Engineering', 'Dual Degree Aerospace', 'M.Tech Aerospace Engineering'],
        eligibility: '10+2 with PCM. Admission through JEE Advanced rank.',
        imageUrl: 'https://picsum.photos/seed/iitbaero/600/400',
        about: 'IIT Bombay offers one of the best Aerospace Engineering programs in India with state-of-the-art laboratories and wind tunnels.',
        level: 'after_12th',
        fee: 'Rs. 2,25,000 per year (Tuition)',
        scholarships: 'Merit-cum-Means, fee waivers for SC/ST/EWS, Institute scholarships.',
        latitude: 19.1334,
        longitude: 72.9133,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.1334,72.9133',
        contactInfo: {
            phone: '+91-22-2576-4545',
            email: 'aerospace@iitb.ac.in',
            website: 'https://www.aero.iitb.ac.in',
            address: 'IIT Bombay, Powai, Mumbai, Maharashtra 400076'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 per semester',
        mediumOfInstruction: ['English'],
        establishedYear: 1958,
        affiliation: 'Institute of National Importance',
        nirfRank: 3,
        placementRate: 100,
        averagePackage: '20 LPA'
    },

    {
        id: 'iit-kharagpur-aero',
        name: 'Indian Institute of Technology Kharagpur - Aerospace Engineering',
        district: 'Kharagpur',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.Tech Aerospace Engineering', 'Dual Degree in Aerospace Engineering'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitkgpaero/600/400',
        about: 'First IIT to offer Aerospace Engineering with comprehensive research facilities and industry collaborations.',
        level: 'after_12th',
        fee: 'Rs. 2,20,000 per year',
        scholarships: 'Full fee waiver for families with income below Rs. 1 lakh. Partial waivers available.',
        latitude: 22.3149,
        longitude: 87.3105,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.3149,87.3105',
        contactInfo: {
            phone: '+91-3222-255-221',
            email: 'aerospace@iitkgp.ac.in',
            website: 'http://www.iitkgp.ac.in/department/AE',
            address: 'IIT Kharagpur, West Bengal 721302'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 12,000 per semester',
        mediumOfInstruction: ['English'],
        establishedYear: 1951,
        affiliation: 'Institute of National Importance',
        nirfRank: 6,
        placementRate: 98,
        averagePackage: '18 LPA'
    },

    {
        id: 'mit-manipal-aero',
        name: 'Manipal Institute of Technology - Aeronautical Engineering',
        district: 'Udupi',
        state: 'Karnataka',
        type: 'Private (Deemed)',
        courses: ['B.Tech Aeronautical Engineering', 'M.Tech Aerospace Engineering'],
        eligibility: '10+2 with PCM. Admission through MET exam.',
        imageUrl: 'https://picsum.photos/seed/mitaero/600/400',
        about: 'Top private university offering comprehensive Aeronautical Engineering program with modern facilities.',
        level: 'after_12th',
        fee: 'Rs. 3,50,000 per year',
        scholarships: 'Merit scholarships for top performers, need-based aid available.',
        latitude: 13.3497,
        longitude: 74.7869,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.3497,74.7869',
        contactInfo: {
            phone: '+91-820-292-3000',
            email: 'mit@manipal.edu',
            website: 'https://manipal.edu/mit.html',
            address: 'Manipal, Karnataka 576104'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 1,20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1957,
        affiliation: 'Deemed University',
        nirfRank: 45,
        placementRate: 92,
        averagePackage: '7.5 LPA'
    },

    // Petroleum Engineering
    {
        id: 'upes-dehradun-petroleum',
        name: 'University of Petroleum and Energy Studies (UPES), Dehradun',
        district: 'Dehradun',
        state: 'Uttarakhand',
        type: 'Private',
        courses: ['B.Tech Petroleum Engineering', 'B.Tech Petroleum Refinery Engineering', 'B.Tech Oil & Gas Engineering'],
        eligibility: '10+2 with PCM. Admission through UPESEAT.',
        imageUrl: 'https://picsum.photos/seed/upespet/600/400',
        about: 'India\'s only university dedicated to petroleum and energy studies with strong industry partnerships.',
        level: 'after_12th',
        fee: 'Rs. 3,05,000 per year',
        scholarships: 'Merit and sports scholarships, education loan assistance.',
        latitude: 30.2715,
        longitude: 77.9944,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=30.2715,77.9944',
        contactInfo: {
            phone: '+91-135-275-3000',
            email: 'admissions@upes.ac.in',
            website: 'https://www.upes.ac.in',
            address: 'Energy Acres, Bidholi via Premnagar, Dehradun 248007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 1,40,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 2003,
        affiliation: 'UGC Recognized University',
        nirfRank: 89,
        placementRate: 85,
        averagePackage: '9 LPA'
    },

    {
        id: 'pdpu-gandhinagar',
        name: 'Pandit Deendayal Energy University, Gandhinagar',
        district: 'Gandhinagar',
        state: 'Gujarat',
        type: 'Government',
        courses: ['B.Tech Petroleum Engineering', 'B.Tech Chemical Engineering (Petroleum Refining)'],
        eligibility: '10+2 with PCM. Admission through JEE Main rank.',
        imageUrl: 'https://picsum.photos/seed/pdpu/600/400',
        about: 'State government university focused on energy studies with excellent placement in oil & gas sector.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Gujarat government scholarships, merit scholarships available.',
        latitude: 23.0658,
        longitude: 72.5742,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.0658,72.5742',
        contactInfo: {
            phone: '+91-79-2327-5145',
            email: 'admission@pdpu.ac.in',
            website: 'https://www.pdpu.ac.in',
            address: 'Raisan Village, Gandhinagar, Gujarat 382007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 2007,
        affiliation: 'State University',
        nirfRank: 72,
        placementRate: 90,
        averagePackage: '8.5 LPA'
    },

    {
        id: 'rgipt-raebareli',
        name: 'Rajiv Gandhi Institute of Petroleum Technology, Rae Bareli',
        district: 'Rae Bareli',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['B.Tech Petroleum Engineering', 'B.Tech Chemical Engineering (Petroleum)'],
        eligibility: '10+2 with PCM. Admission via JEE Main.',
        imageUrl: 'https://picsum.photos/seed/rgipt/600/400',
        about: 'Premier institute established by MHRD with collaboration from leading oil PSUs.',
        level: 'after_12th',
        fee: 'Rs. 1,50,000 per year',
        scholarships: 'Central government scholarships, institute merit scholarships.',
        latitude: 26.2285,
        longitude: 81.1505,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.2285,81.1505',
        contactInfo: {
            phone: '+91-535-270-4000',
            email: 'registrar@rgipt.ac.in',
            website: 'https://www.rgipt.ac.in',
            address: 'Mubarakpur, Mukhetia More, Rae Bareli, UP 229316'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 2008,
        affiliation: 'Institute of National Importance',
        nirfRank: 95,
        placementRate: 95,
        averagePackage: '11 LPA'
    },

    // Chemical Engineering
    {
        id: 'ict-mumbai',
        name: 'Institute of Chemical Technology (ICT), Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.Tech Chemical Engineering', 'B.Tech Polymer Engineering', 'B.Tech Pharmaceutical Sciences'],
        eligibility: '10+2 with PCM. Admission through MHT-CET or JEE Main.',
        imageUrl: 'https://picsum.photos/seed/ictmumbai/600/400',
        about: 'India\'s premier chemical technology institute with 100% placement record.',
        level: 'after_12th',
        fee: 'Rs. 85,000 per year',
        scholarships: 'State government scholarships, minority scholarships available.',
        latitude: 19.0228,
        longitude: 72.8557,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.0228,72.8557',
        contactInfo: {
            phone: '+91-22-3361-1001',
            email: 'registrar@ictmumbai.edu.in',
            website: 'https://www.ictmumbai.edu.in',
            address: 'Nathalal Parekh Marg, Matunga, Mumbai 400019'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1933,
        affiliation: 'Deemed University',
        nirfRank: 47,
        placementRate: 100,
        averagePackage: '14 LPA'
    },

    {
        id: 'nit-surathkal-chem',
        name: 'National Institute of Technology Karnataka, Surathkal',
        district: 'Mangalore',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.Tech Chemical Engineering', 'M.Tech Chemical Engineering'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitkchem/600/400',
        about: 'Top NIT with excellent Chemical Engineering department and research facilities.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee remission for SC/ST, income-based waivers.',
        latitude: 12.9995,
        longitude: 74.7937,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9995,74.7937',
        contactInfo: {
            phone: '+91-824-247-3000',
            email: 'registrar@nitk.edu.in',
            website: 'https://www.nitk.ac.in',
            address: 'Surathkal, Mangalore, Karnataka 575025'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'NIT',
        nirfRank: 13,
        placementRate: 94,
        averagePackage: '15 LPA'
    },

    {
        id: 'lnct-nagpur',
        name: 'Laxminarayan Institute of Technology, Nagpur',
        district: 'Nagpur',
        state: 'Maharashtra',
        type: 'Private',
        courses: ['B.Tech Chemical Engineering', 'B.Tech Chemical Technology'],
        eligibility: '10+2 with PCM. Admission through MH CET.',
        imageUrl: 'https://picsum.photos/seed/lnctnag/600/400',
        about: 'Reputed private engineering college in Vidarbha with strong industry tie-ups.',
        level: 'after_12th',
        fee: 'Rs. 95,000 per year',
        scholarships: 'Institute scholarships for meritorious students.',
        latitude: 21.0974,
        longitude: 79.0499,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=21.0974,79.0499',
        contactInfo: {
            phone: '+91-712-220-5000',
            email: 'info@lnct.ac.in',
            website: 'https://www.lnct.ac.in',
            address: 'Amravati Road, Nagpur, Maharashtra 440033'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1942,
        affiliation: 'AICTE',
        placementRate: 82,
        averagePackage: '5.5 LPA'
    },

    // Mining Engineering
    {
        id: 'iit-ism-dhanbad-mining',
        name: 'IIT (ISM) Dhanbad - Mining Engineering',
        district: 'Dhanbad',
        state: 'Jharkhand',
        type: 'Government',
        courses: ['B.Tech Mining Engineering', 'B.Tech Mining Machinery Engineering', 'B.Tech Mineral & Metallurgical Engineering'],
        eligibility: '10+2 with PCM. Admission through JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitism/600/400',
        about: 'India\'s premier mining institute, formerly ISM Dhanbad, now IIT with legacy of 100+ years.',
        level: 'after_12th',
        fee: 'Rs. 2,15,000 per year',
        scholarships: 'Complete fee waiver for economically weaker sections.',
        latitude: 23.8143,
        longitude: 86.4411,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.8143,86.4411',
        contactInfo: {
            phone: '+91-326-223-5204',
            email: 'registrar@iitism.ac.in',
            website: 'https://www.iitism.ac.in',
            address: 'IIT ISM, Dhanbad, Jharkhand 826004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 per semester',
        mediumOfInstruction: ['English'],
        establishedYear: 1926,
        affiliation: 'IIT',
        nirfRank: 15,
        placementRate: 96,
        averagePackage: '16 LPA'
    },

    {
        id: 'nit-rourkela-mining',
        name: 'NIT Rourkela - Mining Engineering',
        district: 'Rourkela',
        state: 'Odisha',
        type: 'Government',
        courses: ['B.Tech Mining Engineering', 'B.Tech Mining & Explosives Engineering'],
        eligibility: '10+2 with PCM. Admission via JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitrmine/600/400',
        about: 'Premier NIT with strong mining engineering program backed by Odisha\'s mineral resources.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Central and state scholarships, fee waivers for reserved categories.',
        latitude: 22.2502,
        longitude: 84.9016,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.2502,84.9016',
        contactInfo: {
            phone: '+91-661-246-2020',
            email: 'registrar@nitrkl.ac.in',
            website: 'https://www.nitrkl.ac.in',
            address: 'NIT Rourkela, Odisha 769008'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 18,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1961,
        affiliation: 'NIT',
        nirfRank: 16,
        placementRate: 90,
        averagePackage: '12 LPA'
    },

    {
        id: 'gcm-khetri',
        name: 'Government College of Mining, Khetri',
        district: 'Jhunjhunu',
        state: 'Rajasthan',
        type: 'Government',
        courses: ['B.Tech Mining Engineering', 'Diploma in Mining Engineering'],
        eligibility: '10+2 with PCM for B.Tech. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/gcmkhetri/600/400',
        about: 'Specialized government mining college in Rajasthan with affordable education.',
        level: 'after_12th',
        fee: 'Rs. 45,000 per year',
        scholarships: 'Rajasthan state scholarships available.',
        latitude: 28.0074,
        longitude: 75.7861,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.0074,75.7861',
        contactInfo: {
            phone: '+91-1597-222-203',
            email: 'gcmkhetri@rajasthan.gov.in',
            website: 'http://gcmkhetri.nic.in',
            address: 'Khetri Nagar, Jhunjhunu, Rajasthan 333504'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1960,
        affiliation: 'AICTE',
        placementRate: 75,
        averagePackage: '4.5 LPA'
    },

    // Please continue with Textile Technology, Medical, and Commerce colleges next...
    // I'll create them in batches to stay organized

    // Metallurgy Engineering
    {
        id: 'nit-jamshedpur-metallurgy',
        name: 'NIT Jamshedpur - Metallurgical & Materials Engineering',
        district: 'Jamshedpur',
        state: 'Jharkhand',
        type: 'Government',
        courses: ['B.Tech Metallurgical & Materials Engineering', 'M.Tech Metallurgy'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitjsr/600/400',
        about: 'NIT in steel city of India, offering excellent metallurgy program with industry exposure.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee waivers for SC/ST/EWS, merit scholarships.',
        latitude: 22.7757,
        longitude: 86.1489,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.7757,86.1489',
        contactInfo: {
            phone: '+91-657-237-3407',
            email: 'registrar@nitjsr.ac.in',
            website: 'https://www.nitjsr.ac.in',
            address: 'Adityapur, Jamshedpur, Jharkhand 831014'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 18,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'NIT',
        nirfRank: 68,
        placementRate: 88,
        averagePackage: '9.5 LPA'
    },

    {
        id: 'bit-sindri-metallurgy',
        name: 'BIT Sindri - Metallurgical Engineering',
        district: 'Dhanbad',
        state: 'Jharkhand',
        type: 'Government',
        courses: ['B.Tech Metallurgical Engineering', 'B.Tech Materials Science'],
        eligibility: '10+2 with PCM. Admission via JCECE.',
        imageUrl: 'https://picsum.photos/seed/bitsindri/600/400',
        about: 'Historic engineering college known for metallurgy and materials science.',
        level: 'after_12th',
        fee: 'Rs. 65,000 per year',
        scholarships: 'Jharkhand state scholarships available.',
        latitude: 23.6869,
        longitude: 86.4777,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.6869,86.4777',
        contactInfo: {
            phone: '+91-326-224-5170',
            email: 'principal@bitsindri.ac.in',
            website: 'http://www.bitsindri.ac.in',
            address: 'PO Sindri Institute, Dhanbad, Jharkhand 828122'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 12,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1949,
        affiliation: 'AICTE',
        placementRate: 78,
        averagePackage: '6.5 LPA'
    },

    {
        id: 'nit-durgapur-metallurgy',
        name: 'NIT Durgapur - Metallurgical & Materials Engineering',
        district: 'Durgapur',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.Tech Metallurgical & Materials Engineering'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitdgp/600/400',
        about: 'Leading NIT in industrial belt with strong metallurgy department.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Central and state government scholarships.',
        latitude: 23.5500,
        longitude: 87.2846,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.5500,87.2846',
        contactInfo: {
            phone: '+91-343-275-4680',
            email: 'registrar@admin.nitdgp.ac.in',
            website: 'https://www.nitdgp.ac.in',
            address: 'Mahatma Gandhi Avenue, Durgapur, WB 713209'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 16,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'NIT',
        nirfRank: 90,
        placementRate: 85,
        averagePackage: '8.2 LPA'
    },

    // Textile Technology
    {
        id: 'psg-textile',
        name: 'PSG College of Technology - Textile Engineering',
        district: 'Coimbatore',
        state: 'Tamil Nadu',
        type: 'Private (Autonomous)',
        courses: ['B.Tech Textile Technology', 'B.Tech Fashion Technology', 'M.Tech Textiles'],
        eligibility: '10+2 with PCM. Admission through TNEA counseling.',
        imageUrl: 'https://picsum.photos/seed/psgtextile/600/400',
        about: 'Premier autonomous institution offering comprehensive textile engineering programs.',
        level: 'after_12th',
        fee: 'Rs. 75,000 per year',
        scholarships: 'Management scholarships, government fee concessions.',
        latitude: 11.0234,
        longitude: 76.9319,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.0234,76.9319',
        contactInfo: {
            phone: '+91-422-257-2177',
            email: 'principal@psgtech.ac.in',
            website: 'https://www.psgtech.edu',
            address: 'Peelamedu, Coimbatore, Tamil Nadu 641004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 45,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1951,
        affiliation: 'Anna University',
        nirfRank: 58,
        placementRate: 92,
        averagePackage: '6.8 LPA'
    },

    {
        id: 'nift-delhi-textile',
        name: 'National Institute of Fashion Technology (NIFT), New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.FTech (Fashion & Apparel Design)', 'B.Des Textile Design', 'B.FTech Knitwear Design'],
        eligibility: '10+2. Admission through NIFT entrance exam.',
        imageUrl: 'https://picsum.photos/seed/niftdelhi/600/400',
        about: 'Premier fashion and textile institute under Ministry of Textiles.',
        level: 'after_12th',
        fee: 'Rs. 2,10,000 per year',
        scholarships: 'Central government scholarships for eligible categories.',
        latitude: 28.5478,
        longitude: 77.2733,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5478,77.2733',
        contactInfo: {
            phone: '+91-11-2653-7851',
            email: 'niftdelhi@nift.ac.in',
            website: 'https://www.nift.ac.in/delhi',
            address: 'Hauz Khas, Near Gulmohar Park, New Delhi 110016'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 85,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1986,
        affiliation: 'Ministry of Textiles',
        nirfRank: 32,
        placementRate: 96,
        averagePackage: '8.5 LPA'
    },

    {
        id: 'sastra-textile',
        name: 'SASTRA Deemed University - Textile & Fashion Technology',
        district: 'Thanjavur',
        state: 'Tamil Nadu',
        type: 'Private (Deemed)',
        courses: ['B.Tech Textile Technology', 'B.Tech Fashion Technology'],
        eligibility: '10+2 with PCM. Admission through JEE Main or +2 marks.',
        imageUrl: 'https://picsum.photos/seed/sastratex/600/400',
        about: 'Reputed deemed university with modern textile engineering facilities.',
        level: 'after_12th',
        fee: 'Rs. 1,80,000 per year',
        scholarships: 'Merit-based scholarships for top scorers.',
        latitude: 10.7610,
        longitude: 79.0183,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=10.7610,79.0183',
        contactInfo: {
            phone: '+91-4362-264-101',
            email: 'admission@sastra.edu',
            website: 'https://www.sastra.edu',
            address: 'Thirumalaisamudram, Thanjavur, Tamil Nadu 613401'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 65,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1984,
        affiliation: 'Deemed University',
        nirfRank: 56,
        placementRate: 89,
        averagePackage: '6 LPA'
    },

    // ==================== MEDICAL & ALLIED HEALTH ====================

    // BDS - Dentistry
    {
        id: 'maulana-azad-dental-delhi',
        name: 'Maulana Azad Institute of Dental Sciences, New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['BDS', 'MDS (Various Specialties)'],
        eligibility: '10+2 with PCB. Admission through NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/maids/600/400',
        about: 'Premier government dental college in India with state-of-the-art facilities.',
        level: 'after_12th',
        fee: 'Rs. 10,000 per year',
        scholarships: 'Government of Delhi scholarships for all categories.',
        latitude: 28.6317,
        longitude: 77.2195,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6317,77.2195',
        contactInfo: {
            phone: '+91-11-2329-1234',
            email: 'registrar@maids.ac.in',
            website: 'http://www.maids.ac.in',
            address: 'Bahadur Shah Zafar Marg, New Delhi 110002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1920,
        affiliation: 'Government of Delhi',
        nirfRank: 4,
        placementRate: 100,
        averagePackage: '8 LPA'
    },

    {
        id: 'govt-dental-mumbai',
        name: 'Government Dental College and Hospital, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['BDS', 'MDS'],
        eligibility: '10+2 with PCB. Admission via NEET-UG and state quota.',
        imageUrl: 'https://picsum.photos/seed/gdcmumbai/600/400',
        about: 'One of Asia\'s oldest dental colleges with excellent clinical exposure.',
        level: 'after_12th',
        fee: 'Rs. 35,000 per year',
        scholarships: 'Maharashtra state scholarships for eligible students.',
        latitude: 18.9633,
        longitude: 72.8308,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9633,72.8308',
        contactInfo: {
            phone: '+91-22-2373-5555',
            email: 'gdchmumbai@gmail.com',
            website: 'http://gdch.edu.in',
            address: 'St. George Hospital Compound, Mumbai 400001'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1881,
        affiliation: 'MUHS Nashik',
        nirfRank: 8,
        placementRate: 95,
        averagePackage: '7 LPA'
    },

    {
        id: 'manipal-dental',
        name: 'Manipal College of Dental Sciences, Mangalore',
        district: 'Mangalore',
        state: 'Karnataka',
        type: 'Private (Deemed)',
        courses: ['BDS', 'MDS (All Specialties)'],
        eligibility: '10+2 with PCB. Admission through NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/manipaldental/600/400',
        about: 'Premier private dental college with international standards.',
        level: 'after_12th',
        fee: 'Rs. 4,50,000 per year',
        scholarships: 'Merit and need-based scholarships available.',
        latitude: 12.9185,
        longitude: 74.8655,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9185,74.8655',
        contactInfo: {
            phone: '+91-824-242-1170',
            email: 'mcods@manipal.edu',
            website: 'https://manipal.edu/mcods.html',
            address: 'Light House Hill Road, Mangalore, Karnataka 575001'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 1,20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1987,
        affiliation: 'Deemed University',
        nirfRank: 12,
        placementRate: 98,
        averagePackage: '9 LPA'
    },

    // Physiotherapy (BPT)
    {
        id: 'kmc-mangalore-physio',
        name: 'KMC Mangalore - Kasturba Medical College (Physiotherapy)',
        district: 'Mangalore',
        state: 'Karnataka',
        type: 'Private (Deemed)',
        courses: ['BPT (Bachelor of Physiotherapy)', 'MPT'],
        eligibility: '10+2 with PCB. Admission through NEET or university entrance.',
        imageUrl: 'https://picsum.photos/seed/kmcphysio/600/400',
        about: 'Renowned medical college offering excellent physiotherapy programs.',
        level: 'after_12th',
        fee: 'Rs. 2,50,000 per year',
        scholarships: 'University merit scholarships available.',
        latitude: 12.8955,
        longitude: 74.8494,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.8955,74.8494',
        contactInfo: {
            phone: '+91-824-242-1111',
            email: 'kmc@manipal.edu',
            website: 'https://manipal.edu/kmc-mangalore.html',
            address: 'Madhav Nagar, Mangalore, Karnataka 575001'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 95,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1953,
        affiliation: 'Deemed University',
        nirfRank: 7,
        placementRate: 95,
        averagePackage: '4.5 LPA'
    },

    {
        id: 'mahe-physio',
        name: 'Manipal College of Allied Health Sciences (Physiotherapy)',
        district: 'Udupi',
        state: 'Karnataka',
        type: 'Private (Deemed)',
        courses: ['BPT', 'MPT (Sports Physiotherapy)', 'MPT (Neuro)'],
        eligibility: '10+2 with PCB. Admission via Manipal Entrance Test.',
        imageUrl: 'https://picsum.photos/seed/mahephysio/600/400',
        about: 'Specialized college for allied health sciences with modern rehabilitation centers.',
        level: 'after_12th',
        fee: 'Rs. 2,25,000 per year',
        scholarships: 'Merit scholarships and financial aid for deserving students.',
        latitude: 13.3497,
        longitude: 74.7869,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.3497,74.7869',
        contactInfo: {
            phone: '+91-820-257-1201',
            email: 'mcahs@manipal.edu',
            website: 'https://manipal.edu/mcahs.html',
            address: 'Manipal Academy of Higher Education, Manipal 576104'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 1,00,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1997,
        affiliation: 'Deemed University',
        placementRate: 92,
        averagePackage: '4.2 LPA'
    },

    // Medical Lab Technology (MLT)
    {
        id: 'jipmer-puducherry-mlt',
        name: 'JIPMER Puducherry - Medical Lab Technology',
        district: 'Puducherry',
        state: 'Puducherry',
        type: 'Government',
        courses: ['B.Sc Medical Lab Technology', 'M.Sc MLT'],
        eligibility: '10+2 with PCB. Admission through institute entrance exam.',
        imageUrl: 'https://picsum.photos/seed/jipmermlt/600/400',
        about: 'Premier medical institute offering allied health science programs.',
        level: 'after_12th',
        fee: 'Rs. 5,000 per year',
        scholarships: 'Central government scholarships, free education for many.',
        latitude: 11.9416,
        longitude: 79.8083,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.9416,79.8083',
        contactInfo: {
            phone: '+91-413-229-7000',
            email: 'jipmer@jipmer.edu.in',
            website: 'https://www.jipmer.edu.in',
            address: 'Dhanvantari Nagar, Puducherry 605006'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 12,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1956,
        affiliation: 'Institute of National Importance',
        nirfRank: 11,
        placementRate: 100,
        averagePackage: '4 LPA'
    },

    {
        id: 'pgimer-chandigarh-mlt',
        name: 'PGIMER Chandigarh - Medical Lab Sciences',
        district: 'Chandigarh',
        state: 'Chandigarh',
        type: 'Government',
        courses: ['B.Sc Medical Lab Science', 'M.Sc Medical Lab Science'],
        eligibility: '10+2 with PCB. Admission through entrance test.',
        imageUrl: 'https://picsum.photos/seed/pgimermlt/600/400',
        about: 'Top-ranked medical institute with excellent lab sciences program.',
        level: 'after_12th',
        fee: 'Rs. 8,000 per year',
        scholarships: 'Government scholarships and stipends during training.',
        latitude: 30.7660,
        longitude: 76.7750,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=30.7660,76.7750',
        contactInfo: {
            phone: '+91-172-275-4825',
            email: 'registrar@pgimer.edu.in',
            website: 'https://pgimer.edu.in',
            address: 'Sector 12, Chandigarh 160012'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1962,
        affiliation: 'Institute of National Importance',
        nirfRank: 5,
        placementRate: 100,
        averagePackage: '4.5 LPA'
    },

    // ==================== COMMERCE SPECIALIZATIONS ====================

    // Financial Markets
    {
        id: 'hr-college-mumbai-fm',
        name: 'H.R. College of Commerce & Economics, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Private (Autonomous)',
        courses: ['B.Com (Financial Markets)', 'B.Com (Banking & Insurance)', 'BMS (Finance)'],
        eligibility: '10+2. Admission based on merit and entrance test.',
        imageUrl: 'https://picsum.photos/seed/hrcollege/600/400',
        about: 'Premier commerce college in Mumbai known for finance and financial markets programs.',
        level: 'after_12th',
        fee: 'Rs. 45,000 per year',
        scholarships: 'Merit-based scholarships from college trust.',
        latitude: 19.0049,
        longitude: 72.8150,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.0049,72.8150',
        contactInfo: {
            phone: '+91-22-2281-5651',
            email: 'principal@hrcollege.edu',
            website: 'http://hrcollege.edu',
            address: '123, Dinshaw Wachha Road, Churchgate, Mumbai 400020'
        },
        hostelAvailable: false,
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'University of Mumbai',
        placementRate: 95,
        averagePackage: '6.5 LPA'
    },

    {
        id: 'mithibai-mumbai-fm',
        name: 'Mithibai College of Arts, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Private (Autonomous)',
        courses: ['B.Com (Financial Markets)', 'BMS', 'B.Com (Accounting & Finance)'],
        eligibility: '10+2. Merit-based admission.',
        imageUrl: 'https://picsum.photos/seed/mithibai/600/400',
        about: 'Top autonomous college offering specialized commerce programs.',
        level: 'after_12th',
        fee: 'Rs. 35,000 per year',
        scholarships: 'Government and trust scholarships available.',
        latitude: 19.1029,
        longitude: 72.8360,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.1029,72.8360',
        contactInfo: {
            phone: '+91-22-2624-2705',
            email: 'principal@mithibai.ac.in',
            website: 'https://mithibai.ac.in',
            address: 'Vile Parle (West), Mumbai, Maharashtra 400056'
        },
        hostelAvailable: false,
        mediumOfInstruction: ['English'],
        establishedYear: 1961,
        affiliation: 'University of Mumbai',
        placementRate: 92,
        averagePackage: '5.8 LPA'
    },

    {
        id: 'jaihind-mumbai-fm',
        name: 'Jai Hind College, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Private (Autonomous)',
        courses: ['B.Com (Financial Markets)', 'BMS', 'B.A. Economics'],
        eligibility: '10+2. Admission through merit list.',
        imageUrl: 'https://picsum.photos/seed/jaihind/600/400',
        about: 'Prestigious college known for commerce and management education.',
        level: 'after_12th',
        fee: 'Rs. 32,000 per year',
        scholarships: 'College scholarships for meritorious students.',
        latitude: 18.9596,
        longitude: 72.8134,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9596,72.8134',
        contactInfo: {
            phone: '+91-22-2204-8881',
            email: 'jaihindedn@gmail.com',
            website: 'https://jaihindcollege.com',
            address: 'A Road, Churchgate, Mumbai 400020'
        },
        hostelAvailable: false,
        mediumOfInstruction: ['English'],
        establishedYear: 1948,
        affiliation: 'University of Mumbai',
        placementRate: 90,
        averagePackage: '5.5 LPA'
    },

    // International Accounting
    {
        id: 'symbiosis-pune-accounting',
        name: 'Symbiosis College of Arts & Commerce, Pune',
        district: 'Pune',
        state: 'Maharashtra',
        type: 'Private (Deemed)',
        courses: ['B.Com (International Accounting)', 'BBA (Accounting & Finance)', 'B.Com (Professional)'],
        eligibility: '10+2. Admission through SET entrance exam.',
        imageUrl: 'https://picsum.photos/seed/symbiosiscom/600/400',
        about: 'Part of Symbiosis International offering globally recognized commerce programs.',
        level: 'after_12th',
        fee: 'Rs. 1,20,000 per year',
        scholarships: 'Merit-based scholarships from Symbiosis.',
        latitude: 18.5089,
        longitude: 73.8131,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.5089,73.8131',
        contactInfo: {
            phone: '+91-20-2528-1364',
            email: 'scac@symbiosis.ac.in',
            website: 'https://www.scac.edu.in',
            address: 'Senapati Bapat Road, Pune, Maharashtra 411004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 95,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1983,
        affiliation: 'Deemed University',
        placementRate: 94,
        averagePackage: '6 LPA'
    },

    {
        id: 'mount-carmel-bangalore',
        name: 'Mount Carmel College, Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Private (Autonomous)',
        courses: ['B.Com (Professional)', 'B.Com (International Accounting)', 'BBA'],
        eligibility: '10+2. Admission based on merit. Women only.',
        imageUrl: 'https://picsum.photos/seed/mountcarmel/600/400',
        about: 'Premier women\'s college offering specialized commerce programs.',
        level: 'after_12th',
        fee: 'Rs. 65,000 per year',
        scholarships: 'College and government scholarships for eligible students.',
        latitude: 12.9726,
        longitude: 77.6050,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9726,77.6050',
        contactInfo: {
            phone: '+91-80-2299-7700',
            email: 'principal@mcc.edu.in',
            website: 'https://mccblr.edu.in',
            address: '58, Palace Road, Bangalore, Karnataka 560052'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 75,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1948,
        affiliation: 'Bengaluru City University',
        placementRate: 91,
        averagePackage: '5.2 LPA'
    },

    {
        id: 'wcc-chennai-accounting',
        name: 'Women\'s Christian College, Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Private (Autonomous)',
        courses: ['B.Com (Corporate Secretaryship)', 'B.Com (International Business)', 'B.Sc. Visual Communication'],
        eligibility: '10+2. Admission based on merit. Women only.',
        imageUrl: 'https://picsum.photos/seed/wccchennai/600/400',
        about: 'Historic women\'s college offering diverse undergraduate programs.',
        level: 'after_12th',
        fee: 'Rs. 28,000 per year',
        scholarships: 'Government and college scholarships available.',
        latitude: 13.0624,
        longitude: 80.2571,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0624,80.2571',
        contactInfo: {
            phone: '+91-44-2833-6173',
            email: 'principal@wcc.edu.in',
            website: 'https://www.wcc.edu.in',
            address: 'College Road, Nungambakkam, Chennai 600006'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 55,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1915,
        affiliation: 'University of Madras',
        placementRate: 88,
        averagePackage: '4.8 LPA'
    },

    // ==================== ARCHITECTURE ====================

    {
        id: 'spa-delhi',
        name: 'School of Planning and Architecture (SPA), New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.Arch', 'B.Planning', 'M.Arch'],
        eligibility: '10+2 with PCM and 50% aggregate. Admission through JEE Main Paper 2 and NATA.',
        imageUrl: 'https://picsum.photos/seed/spadelhi/600/400',
        about: 'Premier architecture institute in India with autonomous status.',
        level: 'after_12th',
        fee: 'Rs. 45,000 per year',
        scholarships: 'Central government scholarships for all categories.',
        latitude: 28.6315,
        longitude: 77.2192,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6315,77.2192',
        contactInfo: {
            phone: '+91-11-2338-5582',
            email: 'registrar@spa.ac.in',
            website: 'http://www.spa.ac.in',
            address: 'Indraprastha Estate, New Delhi 110002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1941,
        affiliation: 'Deemed University',
        nirfRank: 21,
        placementRate: 96,
        averagePackage: '8 LPA'
    },

    {
        id: 'cept-ahmedabad',
        name: 'CEPT University, Ahmedabad',
        district: 'Ahmedabad',
        state: 'Gujarat',
        type: 'Private (Deemed)',
        courses: ['B.Arch', 'B.Planning', 'B.Des (Interior Design)'],
        eligibility: '10+2 with 50% marks. Admission through NATA and university aptitude test.',
        imageUrl: 'https://picsum.photos/seed/ceptamd/600/400',
        about: 'Leading architecture and planning university with international recognition.',
        level: 'after_12th',
        fee: 'Rs. 2,75,000 per year',
        scholarships: 'Merit scholarships and financial aid for deserving students.',
        latitude: 23.0395,
        longitude: 72.5580,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.0395,72.5580',
        contactInfo: {
            phone: '+91-79-2630-2470',
            email: 'registrar@cept.ac.in',
            website: 'https://www.cept.ac.in',
            address: 'Navrangpura, Ahmedabad, Gujarat 380009'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 80,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1962,
        affiliation: 'Deemed University',
        nirfRank: 33,
        placementRate: 93,
        averagePackage: '7.5 LPA'
    },

    // ==================== LAW ====================

    {
        id: 'nlu-delhi',
        name: 'National Law University, Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.A. LL.B (Hons)', 'B.Com LL.B (Hons)', 'LL.M'],
        eligibility: '10+2. Admission through CLAT (Common Law Admission Test).',
        imageUrl: 'https://picsum.photos/seed/nludelhi/600/400',
        about: 'Premier national law university offering integrated law programs.',
        level: 'after_12th',
        fee: 'Rs. 2,50,000 per year',
        scholarships: 'Merit-cum-means scholarships, fee waivers for economically weaker sections.',
        latitude: 28.5355,
        longitude: 77.2710,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5355,77.2710',
        contactInfo: {
            phone: '+91-11-2804-1148',
            email: 'registrar@nludelhi.ac.in',
            website: 'http://www.nludelhi.ac.in',
            address: 'Sector 14, Dwarka, New Delhi 110078'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 95,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 2008,
        affiliation: 'State University',
        nirfRank: 4,
        placementRate: 98,
        averagePackage: '12 LPA'
    },

    {
        id: 'nalsar-hyderabad',
        name: 'NALSAR University of Law, Hyderabad',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.A. LL.B (Hons)', 'B.A. LL.B + LL.M (Hons)', 'B.Sc. LL.B (Hons)'],
        eligibility: '10+2. Admission through CLAT.',
        imageUrl: 'https://picsum.photos/seed/nalsar/600/400',
        about: 'Top-ranked national law school with excellent academic environment.',
        level: 'after_12th',
        fee: 'Rs. 2,30,000 per year',
        scholarships: 'Financial assistance for economically disadvantaged students.',
        latitude: 17.4580,
        longitude: 78.3820,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.4580,78.3820',
        contactInfo: {
            phone: '+91-40-2349-8001',
            email: 'registrar@nalsar.ac.in',
            website: 'https://www.nalsar.ac.in',
            address: 'Justice City, Shameerpet, Hyderabad 500101'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 85,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1998,
        affiliation: 'State University',
        nirfRank: 3,
        placementRate: 99,
        averagePackage: '14 LPA'
    },

    {
        id: 'nls-bangalore',
        name: 'National Law School of India University, Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.A. LL.B (Hons)', 'LL.M', 'M.Phil in Law'],
        eligibility: '10+2. Admission via CLAT.',
        imageUrl: 'https://picsum.photos/seed/nlsiu/600/400',
        about: 'India\'s first and most prestigious national law university.',
        level: 'after_12th',
        fee: 'Rs. 2,20,000 per year',
        scholarships: 'Merit scholarships and need-based financial aid.',
        latitude: 13.0082,
        longitude: 77.5673,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0082,77.5673',
        contactInfo: {
            phone: '+91-80-2316-0532',
            email: 'registrar@nls.ac.in',
            website: 'https://www.nls.ac.in',
            address: 'Nagarbhavi, Bangalore, Karnataka 560242'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 75,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1987,
        affiliation: 'State University',
        nirfRank: 1,
        placementRate: 100,
        averagePackage: '15 LPA'
    },

    // ==================== VISUAL COMMUNICATION ====================

    {
        id: 'mcc-chennai-viscom',
        name: 'Madras Christian College - Visual Communication',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Private (Autonomous)',
        courses: ['B.Sc. Visual Communication', 'M.A. Communication'],
        eligibility: '10+2. Admission based on merit and interview.',
        imageUrl: 'https://picsum.photos/seed/mccviscom/600/400',
        about: 'Pioneering college in visual communication with state-of-the-art studios.',
        level: 'after_12th',
        fee: 'Rs. 45,000 per year',
        scholarships: 'College and government scholarships available.',
        latitude: 12.9226,
        longitude: 80.1274,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9226,80.1274',
        contactInfo: {
            phone: '+91-44-2239-0675',
            email: 'principal@mcc.edu.in',
            website: 'https://mcc.edu.in',
            address: 'Tambaram, Chennai, Tamil Nadu 600059'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 35,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1837,
        affiliation: 'University of Madras',
        nirfRank: 16,
        placementRate: 85,
        averagePackage: '4.5 LPA'
    },

    {
        id: 'wcc-chennai-viscom',
        name: 'Women\'s Christian College - Visual Communication',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Private (Autonomous)',
        courses: ['B.Sc. Visual Communication', 'B.Sc. Electronic Media'],
        eligibility: '10+2. Admission based on merit. Women only.',
        imageUrl: 'https://picsum.photos/seed/wccviscom/600/400',
        about: 'Top women\'s college offering comprehensive media and visual communication programs.',
        level: 'after_12th',
        fee: 'Rs. 32,000 per year',
        scholarships: 'Government and college scholarships available.',
        latitude: 13.0624,
        longitude: 80.2571,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0624,80.2571',
        contactInfo: {
            phone: '+91-44-2833-6173',
            email: 'principal@wcc.edu.in',
            website: 'https://www.wcc.edu.in',
            address: 'College Road, Nungambakkam, Chennai 600006'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 55,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1915,
        affiliation: 'University of Madras',
        placementRate: 82,
        averagePackage: '4 LPA'
    },

];
