import type { College } from './types';

/**
 * Additional Government Colleges Database
 * 
 * Instructions for adding more colleges in the future:
 * 1. Copy the template below
 * 2. Fill in real, verified data
 * 3. Required fields: all except optional ones marked with ?
 * 4. Get coordinates from Google Maps
 * 5. Verify contact info from official website
 */

export const additionalColleges: College[] = [
    // ==================== ANDHRA PRADESH & TELANGANA ====================
    {
        id: 'spmvv-tirupati',
        name: 'Sri Padmavati Mahila Visvavidyalayam, Tirupati',
        district: 'Tirupati',
        state: 'Andhra Pradesh',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Biotechnology'],
        eligibility: '10+2. Women-only university.',
        imageUrl: 'https://picsum.photos/seed/spmvv/600/400',
        about: 'Indias first state-funded womens university, dedicated to empowering women through quality education in arts, science, and commerce.',
        level: 'after_12th',
        fee: 'Rs. 8,000 - Rs. 15,000 per year',
        scholarships: 'State government scholarships for SC/ST/OBC/Minority/EWS.',
        latitude: 13.6333,
        longitude: 79.4167,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.6333,79.4167',
        contactInfo: {
            phone: '+91-877-228-7007',
            email: 'info@spmvv.ac.in',
            website: 'https://www.spmvv.ac.in',
            address: 'Tirupati, Andhra Pradesh 517502'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 10,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Telugu'],
        establishedYear: 1983,
        affiliation: 'State University',
        placementRate: 55,
        averagePackage: '3.5 LPA'
    },

    {
        id: 'jntuh-ceh',
        name: 'JNTUH College of Engineering, Hyderabad',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Tech Civil'],
        eligibility: '10+2 with PCM. Admission through TS EAMCET.',
        imageUrl: 'https://picsum.photos/seed/jntuhceh/600/400',
        about: 'Constituent college of JNTU Hyderabad, known for excellent technical education and strong industry connections.',
        level: 'after_12th',
        fee: 'Rs. 35,000 - Rs. 40,000 per year',
        scholarships: 'TS Fee Reimbursement Scheme available for eligible students.',
        latitude: 17.5081,
        longitude: 78.3947,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.5081,78.3947',
        contactInfo: {
            phone: '+91-40-2315-6103',
            email: 'principal@jntuhceh.ac.in',
            website: 'https://jntuhceh.ac.in',
            address: 'Kukatpally, Hyderabad 500085'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 - Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1965,
        affiliation: 'JNTUH',
        placementRate: 85,
        averagePackage: '7.5 LPA'
    },

    {
        id: 'kakatiya-univ',
        name: 'Kakatiya University, Warangal',
        district: 'Warangal',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission through DOST counseling.',
        imageUrl: 'https://picsum.photos/seed/kakatiya/600/400',
        about: 'Premier state university in Telangana, known for science and arts programs with excellent research facilities.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 20,000 per year',
        scholarships: 'Telangana state scholarships available for various categories.',
        latitude: 17.9784,
        longitude: 79.5941,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.9784,79.5941',
        contactInfo: {
            phone: '+91-870-245-9000',
            email: 'registrar@kakatiya.ac.in',
            website: 'https://www.kakatiya.ac.in',
            address: 'Vidyaranyapuri, Warangal 506009'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 15,000 per year',
        mediumOfInstruction: ['English', 'Telugu'],
        establishedYear: 1976,
        affiliation: 'State University',
        placementRate: 60,
        averagePackage: '4.0 LPA'
    },

    // ==================== TAMIL NADU ====================
    {
        id: 'madras-univ',
        name: 'University of Madras, Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Visual Communication'],
        eligibility: '10+2. Admission based on 12th marks.',
        imageUrl: 'https://picsum.photos/seed/madrasuniv/600/400',
        about: 'One of Indias oldest universities, established in 1857. Offers comprehensive undergraduate and postgraduate programs.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 12,000 per year',
        scholarships: 'TN government scholarships for various categories.',
        latitude: 13.0569,
        longitude: 80.2497,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0569,80.2497',
        contactInfo: {
            phone: '+91-44-2539-5224',
            email: 'registrar@unom.ac.in',
            website: 'https://www.unom.ac.in',
            address: 'Chepauk, Chennai 600005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 12,000 per year',
        mediumOfInstruction: ['English', 'Tamil'],
        establishedYear: 1857,
        affiliation: 'State University',
        nirfRank: 28,
        placementRate: 70,
        averagePackage: '6 LPA'
    },

    {
        id: 'govt-arts-cbe',
        name: 'Government Arts College, Coimbatore',
        district: 'Coimbatore',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['B.A. English', 'B.A. Tamil', 'B.Sc. Maths', 'B.Sc. Physics', 'B.Com'],
        eligibility: '10+2. Admission based on marks.',
        imageUrl: 'https://picsum.photos/seed/cbearts/600/400',
        about: 'Premier government arts college in Coimbatore with excellent track record since 1875.',
        level: 'after_12th',
        fee: 'Rs. 1,500 - Rs. 5,000 per year',
        scholarships: 'State scholarships and fee concessions available.',
        latitude: 11.0168,
        longitude: 76.9558,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.0168,76.9558',
        contactInfo: {
            phone: '+91-422-239-1268',
            email: 'gaccbe@tn.gov.in',
            website: 'http://www.gacbe.ac.in',
            address: 'Avinashi Road, Coimbatore 641018'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 - Rs. 10,000 per year',
        mediumOfInstruction: ['English', 'Tamil'],
        establishedYear: 1875,
        affiliation: 'Bharathiar University',
        placementRate: 55,
        averagePackage: '2.8 LPA'
    },

    // ==================== KARNATAKA ====================
    {
        id: 'bangalore-univ',
        name: 'Bangalore University, Bengaluru',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission through university counseling.',
        imageUrl: 'https://picsum.photos/seed/bloreuniv/600/400',
        about: 'Major state university in Karnataka with multiple constituent colleges across the state.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 15,000 per year',
        scholarships: 'Karnataka state scholarships for SC/ST/OBC.',
        latitude: 12.9716,
        longitude: 77.5946,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9716,77.5946',
        contactInfo: {
            phone: '+91-80-2296-1315',
            email: 'registrar@bangaloreuniversity.ac.in',
            website: 'https://www.bangaloreuniversity.ac.in',
            address: 'Jnana Bharathi Campus, Bengaluru 560056'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Kannada'],
        establishedYear: 1964,
        affiliation: 'State University',
        placementRate: 65,
        averagePackage: '4.5 LPA'
    },

    {
        id: 'gec-hassan',
        name: 'Government Engineering College, Hassan',
        district: 'Hassan',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.E. Civil', 'B.E. Mechanical', 'B.E. ECE', 'B.E. CSE'],
        eligibility: '10+2 with PCM. Admission through KCET.',
        imageUrl: 'https://picsum.photos/seed/hassanengg/600/400',
        about: 'Government engineering college in Hassan district with strong technical programs.',
        level: 'after_12th',
        fee: 'Rs. 20,000 - Rs. 30,000 per year',
        scholarships: 'State fee reimbursement for eligible students.',
        latitude: 13.0050,
        longitude: 76.0965,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0050,76.0965',
        contactInfo: {
            phone: '+91-8172-268-003',
            email: 'principal@gechassan.ac.in',
            website: 'http://www.gechassan.ac.in',
            address: 'B.M. Road, Hassan 573201'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 12,000 - Rs. 20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1963,
        affiliation: 'VTU',
        placementRate: 75,
        averagePackage: '4.5 LPA'
    },

    // ==================== MAHARASHTRA ====================
    {
        id: 'mumbai-univ',
        name: 'University of Mumbai, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BMS', 'B.Sc. IT'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/mumbaiuniv/600/400',
        about: 'Premier state university in Mumbai, one of the largest in the world with over 700 affiliated colleges.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 20,000 per year',
        scholarships: 'Maharashtra state scholarships available for various categories.',
        latitude: 18.9750,
        longitude: 72.8258,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9750,72.8258',
        contactInfo: {
            phone: '+91-22-2652-7654',
            email: 'info@mu.ac.in',
            website: 'https://www.mu.ac.in',
            address: 'Kalina Campus, Santacruz East, Mumbai 400098'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 - Rs. 30,000 per year',
        mediumOfInstruction: ['English', 'Marathi'],
        establishedYear: 1857,
        affiliation: 'State University',
        nirfRank: 41,
        placementRate: 72
    },

    {
        id: 'pune-univ',
        name: 'Savitribai Phule Pune University, Pune',
        district: 'Pune',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Computer Science'],
        eligibility: '10+2. Admission through university counseling.',
        imageUrl: 'https://picsum.photos/seed/puneuniv/600/400',
        about: 'Major state university in Pune, formerly University of Pune, with strong research focus.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 15,000 per year',
        scholarships: 'State and central government scholarships available.',
        latitude: 18.5089,
        longitude: 73.8174,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.5089,73.8174',
        contactInfo: {
            phone: '+91-20-2560-1001',
            email: 'registrar@unipune.ac.in',
            website: 'http://www.unipune.ac.in',
            address: 'Ganeshkhind, Pune 411007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 20,000 per year',
        mediumOfInstruction: ['English', 'Marathi'],
        establishedYear: 1949,
        affiliation: 'State University',
        nirfRank: 39,
        placementRate: 68
    },

    // ==================== WEST BENGAL ====================
    {
        id: 'calcutta-univ',
        name: 'University of Calcutta, Kolkata',
        district: 'Kolkata',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/calcuttauniv/600/400',
        about: 'One of the oldest universities in India, established in 1857. Rich heritage in arts and sciences.',
        level: 'after_12th',
        fee: 'Rs. 2,000 - Rs. 10,000 per year',
        scholarships: 'State and central scholarships available.',
        latitude: 22.5726,
        longitude: 88.3639,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.5726,88.3639',
        contactInfo: {
            phone: '+91-33-2241-0071',
            email: 'registrar@caluniv.ac.in',
            website: 'https://www.caluniv.ac.in',
            address: 'College Street, Kolkata 700073'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 - Rs. 12,000 per year',
        mediumOfInstruction: ['English', 'Bengali'],
        establishedYear: 1857,
        affiliation: 'State University',
        nirfRank: 25,
        placementRate: 70,
        averagePackage: '5.2 LPA'
    },

    // ==================== UTTAR PRADESH ====================
    {
        id: 'lucknow-univ',
        name: 'University of Lucknow, Lucknow',
        district: 'Lucknow',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on entrance test.',
        imageUrl: 'https://picsum.photos/seed/lucknowuniv/600/400',
        about: 'Premier state university in Uttar Pradesh with comprehensive academic programs.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 15,000 per year',
        scholarships: 'UP government scholarships available.',
        latitude: 26.8467,
        longitude: 80.9462,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.8467,80.9462',
        contactInfo: {
            phone: '+91-522-274-0003',
            email: 'info@lkouniv.ac.in',
            website: 'https://www.lkouniv.ac.in',
            address: 'University Road, Lucknow 226007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1920,
        affiliation: 'State University',
        placementRate: 62,
        averagePackage: '4.2 LPA'
    },

    {
        id: 'allahabad-univ',
        name: 'University of Allahabad, Prayagraj',
        district: 'Prayagraj',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'LLB', 'BCA'],
        eligibility: '10+2. Admission through entrance test.',
        imageUrl: 'https://picsum.photos/seed/allahabaduniv/600/400',
        about: 'Central university, one of the oldest in India with strong academic heritage.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 12,000 per year',
        scholarships: 'Central and state scholarships available.',
        latitude: 25.4358,
        longitude: 81.8463,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.4358,81.8463',
        contactInfo: {
            phone: '+91-532-246-0993',
            email: 'registrar@allduniv.ac.in',
            website: 'https://www.allduniv.ac.in',
            address: 'Senate House Campus, Prayagraj 211002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 15,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1887,
        affiliation: 'Central University',
        nirfRank: 43,
        placementRate: 65
    },

    // ==================== RAJASTHAN ====================
    {
        id: 'rajasthan-univ',
        name: 'University of Rajasthan, Jaipur',
        district: 'Jaipur',
        state: 'Rajasthan',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/rajasthanuniv/600/400',
        about: 'Oldest university in Rajasthan state, established right after independence.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 15,000 per year',
        scholarships: 'Rajasthan state scholarships available.',
        latitude: 26.9124,
        longitude: 75.7873,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.9124,75.7873',
        contactInfo: {
            phone: '+91-141-270-6106',
            email: 'info@uniraj.ac.in',
            website: 'https://www.uniraj.ac.in',
            address: 'JLN Marg, Jaipur 302004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 16,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1947,
        affiliation: 'State University',
        placementRate: 60,
        averagePackage: '4.0 LPA'
    },

    // ==================== GUJARAT ====================
    {
        id: 'gujarat-univ',
        name: 'Gujarat University, Ahmedabad',
        district: 'Ahmedabad',
        state: 'Gujarat',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/gujaratuniv/600/400',
        about: 'Major state university in Gujarat, one of the oldest and largest in the state.',
        level: 'after_12th',
        fee: 'Rs. 4,000 - Rs. 12,000 per year',
        scholarships: 'Gujarat state scholarships for SC/ST/SEBC/EWS.',
        latitude: 23.0225,
        longitude: 72.5714,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=23.0225,72.5714',
        contactInfo: {
            phone: '+91-79-2630-6856',
            email: 'registrar@gujaratuniversity.ac.in',
            website: 'https://www.gujaratuniversity.ac.in',
            address: 'Navrangpura, Ahmedabad 380009'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 15,000 per year',
        mediumOfInstruction: ['English', 'Gujarati', 'Hindi'],
        establishedYear: 1949,
        affiliation: 'State University',
        placementRate: 64,
        averagePackage: '4.8 LPA'
    },

    {
        id: 'ms-univ-baroda',
        name: 'Maharaja Sayajirao University of Baroda, Vadodara',
        district: 'Vadodara',
        state: 'Gujarat',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. IT'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/msuniv/600/400',
        about: 'Premier university in Gujarat with strong academic reputation and research facilities.',
        level: 'after_12th',
        fee: 'Rs. 5,000 - Rs. 18,000 per year',
        scholarships: 'State and central government scholarships available.',
        latitude: 22.3072,
        longitude: 73.1812,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.3072,73.1812',
        contactInfo: {
            phone: '+91-265-279-5201',
            email: 'registrar@msubaroda.ac.in',
            website: 'https://www.msubaroda.ac.in',
            address: 'Pratapgunj, Vadodara 390002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 10,000 - Rs. 20,000 per year',
        mediumOfInstruction: ['English', 'Gujarati'],
        establishedYear: 1949,
        affiliation: 'State University',
        nirfRank: 31,
        placementRate: 70,
        averagePackage: '5.5 LPA'
    },

    // ==================== BIHAR ====================
    {
        id: 'patna-univ',
        name: 'Patna University, Patna',
        district: 'Patna',
        state: 'Bihar',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/patnauniv/600/400',
        about: 'One of the oldest universities in India, established in 1917. Major center for education in Bihar.',
        level: 'after_12th',
        fee: 'Rs. 3,000 - Rs. 10,000 per year',
        scholarships: 'Bihar state scholarships and central schemes available.',
        latitude: 25.6093,
        longitude: 85.1376,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.6093,85.1376',
        contactInfo: {
            phone: '+91-612-2232-568',
            email: 'registrar@patnauniversity.ac.in',
            website: 'http://www.patnauniversity.ac.in',
            address: 'Ashok Rajpath, Patna 800005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 12,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1917,
        affiliation: 'State University',
        placementRate: 55,
        averagePackage: '3.8 LPA'
    },

    {
        id: 'nit-patna',
        name: 'National Institute of Technology, Patna',
        district: 'Patna',
        state: 'Bihar',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical', 'B.Tech Civil', 'B.Arch'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitpatna/600/400',
        about: 'NIT Patna is one of the premier technical institutes in Eastern India with excellent placement records.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee remission for SC/ST/PwD. Merit scholarships available.',
        latitude: 25.6207,
        longitude: 85.1720,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=25.6207,85.1720',
        contactInfo: {
            phone: '+91-612-237-1715',
            email: 'registrar@nitp.ac.in',
            website: 'https://www.nitp.ac.in',
            address: 'Ashok Rajpath, Patna 800005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 15,000 - Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1886,
        affiliation: 'NIT (Institute of National Importance)',
        nirfRank: 64,
        placementRate: 88,
        averagePackage: '10.5 LPA'
    },

    // ==================== ODISHA ====================
    {
        id: 'utkal-univ',
        name: 'Utkal University, Bhubaneswar',
        district: 'Bhubaneswar',
        state: 'Odisha',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'BCA'],
        eligibility: '10+2. Admission based on Plus Two marks.',
        imageUrl: 'https://picsum.photos/seed/utkaluniv/600/400',
        about: 'Oldest university in Odisha, established in 1943. Major center for higher education in the state.',
        level: 'after_12th',
        fee: 'Rs. 3,500 - Rs. 12,000 per year',
        scholarships: 'Odisha state scholarships and central schemes available.',
        latitude: 20.2961,
        longitude: 85.8245,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=20.2961,85.8245',
        contactInfo: {
            phone: '+91-674-256-7832',
            email: 'registrar@utkaluniversity.ac.in',
            website: 'http://www.utkaluniversity.ac.in',
            address: 'Vani Vihar, Bhubaneswar 751004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 - Rs. 14,000 per year',
        mediumOfInstruction: ['English', 'Odia'],
        establishedYear: 1943,
        affiliation: 'State University',
        placementRate: 58,
        averagePackage: '4.0 LPA'
    },

    {
        id: 'nit-rourkela',
        name: 'National Institute of Technology, Rourkela',
        district: 'Rourkela',
        state: 'Odisha',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech Metallurgical', 'B.Tech Chemical', 'B.Tech Mining', 'B.Arch'],
        eligibility: '10+2 with PCM. Admission through JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitrourkela/600/400',
        about: 'One of the top NITs in India, known for metallurgy and engineering programs.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee waivers for SC/ST and income-based scholarships.',
        latitude: 22.2502,
        longitude: 84.9016,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.2502,84.9016',
        contactInfo: {
            phone: '+91-661-246-2020',
            email: 'registrar@nitrkl.ac.in',
            website: 'https://www.nitrkl.ac.in',
            address: 'Rourkela, Odisha 769008'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 18,000 - Rs. 28,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1961,
        affiliation: 'NIT (Institute of National Importance)',
        nirfRank: 16,
        placementRate: 90,
        averagePackage: '12 LPA'
    },

    // ==================== KERALA ====================
    {
        id: 'kerala-univ',
        name: 'University of Kerala, Thiruvananthapuram',
        district: 'Thiruvananthapuram',
        state: 'Kerala',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Sc. Data Science'],
        eligibility: '10+2. Admission through university allotment.',
        imageUrl: 'https://picsum.photos/seed/keralauniv/600/400',
        about: 'First university in Kerala, established in 1937. Premier institution for higher education in the state.',
        level: 'after_12th',
        fee: 'Rs. 4,000 - Rs. 15,000 per year',
        scholarships: 'Kerala state scholarships for SC/ST/OBC/Minority students.',
        latitude: 8.4801,
        longitude: 76.9491,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=8.4801,76.9491',
        contactInfo: {
            phone: '+91-471-230-7316',
            email: 'universitykl@keralauniversity.ac.in',
            website: 'https://www.keralauniversity.ac.in',
            address: 'Palayam, Thiruvananthapuram 695034'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 - Rs. 18,000 per year',
        mediumOfInstruction: ['English', 'Malayalam'],
        establishedYear: 1937,
        affiliation: 'State University',
        placementRate: 65,
        averagePackage: '4.5 LPA'
    },

    {
        id: 'calicut-univ',
        name: 'University of Calicut, Calicut',
        district: 'Malappuram',
        state: 'Kerala',
        type: 'Government',
        courses: ['B.A.', 'B.Sc.', 'B.Com', 'BBA', 'B.Voc'],
        eligibility: '10+2. Admission through CAP (Centralised Allotment Process).',
        imageUrl: 'https://picsum.photos/seed/calicutuniv/600/400',
        about: 'Largest university in Kerala in terms of student enrollment, established in 1968.',
        level: 'after_12th',
        fee: 'Rs. 3,500 - Rs. 14,000 per year',
        scholarships: 'State and central scholarships for eligible categories.',
        latitude: 11.1246,
        longitude: 75.8364,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.1246,75.8364',
        contactInfo: {
            phone: '+91-494-240-7356',
            email: 'mail@uoc.ac.in',
            website: 'https://www.uoc.ac.in',
            address: 'Thenhipalam, Malappuram 673635'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 7,000 - Rs. 16,000 per year',
        mediumOfInstruction: ['English', 'Malayalam'],
        establishedYear: 1968,
        affiliation: 'State University',
        placementRate: 63,
        averagePackage: '4.2 LPA'
    },


    // ==================== POLYTECHNIC / DIPLOMA COLLEGES ====================
    {
        id: 'govt-poly-mumbai',
        name: 'Government Polytechnic, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['Diploma in Computer Engineering', 'Diploma in Civil Engineering', 'Diploma in Mechanical Engineering', 'Diploma in Electrical Engineering', 'Diploma in Electronics'],
        eligibility: '10th Pass with Science & Maths. Admission via CAP rounds.',
        imageUrl: 'https://picsum.photos/seed/gpmumbai/600/400',
        about: 'One of the oldest and most prestigious polytechnic institutes in Maharashtra, offering autonomous diploma programs.',
        level: 'after_10th',
        fee: 'Rs. 6,000 - Rs. 10,000 per year',
        scholarships: 'MahaDBT scholarships for reserved categories and EBC.',
        latitude: 19.0607,
        longitude: 72.8362,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.0607,72.8362',
        contactInfo: {
            phone: '+91-22-2647-4780',
            email: 'principal@gpmumbai.ac.in',
            website: 'https://gpmumbai.ac.in',
            address: '49, Kherwadi, Ali Yawar Jung Marg, Bandra (East), Mumbai 400051'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'MSBTE (Autonomous)',
        placementRate: 80,
        averagePackage: '3.5 LPA'
    },

    {
        id: 'pusa-poly-delhi',
        name: 'Pusa Institute of Technology, New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['Diploma in Automobile Engineering', 'Diploma in Civil Engineering', 'Diploma in Printing Technology', 'Diploma in Electronics'],
        eligibility: '10th Pass. Admission via Delhi CET.',
        imageUrl: 'https://picsum.photos/seed/pusapoly/600/400',
        about: 'A premier technical institute in Delhi, highly reputed for its engineering diploma courses and placement records.',
        level: 'after_10th',
        fee: 'Rs. 8,000 - Rs. 12,000 per year',
        scholarships: 'Delhi Government scholarships for meritorious students.',
        latitude: 28.6349,
        longitude: 77.1663,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6349,77.1663',
        contactInfo: {
            phone: '+91-11-2584-7238',
            email: 'pit.delhi@nic.in',
            website: 'http://pit.delhi.gov.in',
            address: 'Pusa, New Delhi 110012'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1962,
        affiliation: 'BTE Delhi',
        placementRate: 88,
        averagePackage: '3.8 LPA'
    },
    {
        id: 'govt-poly-pune',
        name: 'Government Polytechnic, Pune',
        district: 'Pune',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['Diploma in Computer Engineering', 'Diploma in IT', 'Diploma in E&TC', 'Diploma in Dress Designing'],
        eligibility: '10th Pass. Admission via Centralized Admission Process (CAP).',
        imageUrl: 'https://picsum.photos/seed/gppune/600/400',
        about: 'An autonomous institute of Government of Maharashtra, known for academic excellence and strong alumni network.',
        level: 'after_10th',
        fee: 'Rs. 7,500 per year',
        scholarships: 'Various state government scholarships.',
        latitude: 18.5324,
        longitude: 73.8335,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.5324,73.8335',
        contactInfo: {
            phone: '+91-20-2567-6818',
            email: 'principal.gppune@dtemaharashtra.gov.in',
            website: 'http://www.gppune.ac.in',
            address: 'University Road, Ganeshkhind, Pune 411016'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 4,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1957,
        affiliation: 'MSBTE (Autonomous)',
        placementRate: 92,
        averagePackage: '4.0 LPA'
    },
    {
        id: 'thiagarajar-poly-salem',
        name: 'Thiagarajar Polytechnic College, Salem',
        district: 'Salem',
        state: 'Tamil Nadu',
        type: 'Government-Aided',
        courses: ['Diploma in Textile Technology', 'Diploma in Civil Engineering', 'Diploma in Mechanical Engineering', 'Diploma in Production Engineering'],
        eligibility: '10th Pass. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/tptsalem/600/400',
        about: 'A highly awarded polytechnic college, famous for its textile technology and mechanical engineering programs.',
        level: 'after_10th',
        fee: 'Rs. 15,000 - Rs. 25,000 per year',
        scholarships: 'State government and management scholarships.',
        latitude: 11.6643,
        longitude: 78.1460,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.6643,78.1460',
        contactInfo: {
            phone: '+91-427-409-9100',
            email: 'principal@tpt.edu.in',
            website: 'https://www.tpt.edu.in',
            address: 'Junction Main Road, Salem, Tamil Nadu 636005'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1958,
        affiliation: 'DOTE Tamil Nadu',
        placementRate: 95,
        averagePackage: '3.8 LPA'
    },

    // ==================== ITI INSTITUTES ====================
    {
        id: 'govt-iti-guindy',
        name: 'Government Industrial Training Institute (ITI), Guindy',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Welder', 'Turner', 'Machinist', 'Motor Mechanic Vehicle'],
        eligibility: '8th/10th Pass. Admission based on district merit list.',
        imageUrl: 'https://picsum.photos/seed/itiguindy/600/400',
        about: 'One of the premier ITIs in Tamil Nadu, offering a wide range of engineering and non-engineering trades.',
        level: 'after_10th',
        fee: 'Rs. 2,000 - Rs. 4,000 per year',
        scholarships: 'Stipend for trainees and scholarships for SC/ST.',
        latitude: 13.0102,
        longitude: 80.2157,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0102,80.2157',
        contactInfo: {
            phone: '+91-44-2250-1002',
            email: 'guindyiti@gmail.com',
            website: 'https://skilltraining.tn.gov.in',
            address: 'Guindy, Chennai, Tamil Nadu 600032'
        },
        hostelAvailable: true,
        hostelFees: 'Minimal charges',
        mediumOfInstruction: ['Tamil', 'English'],
        establishedYear: 1960,
        affiliation: 'NCVT',
        placementRate: 80
    },
    {
        id: 'govt-iti-mumbai',
        name: 'Government Industrial Training Institute, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Draughtsman Civil', 'Information Technology', 'Refrigeration & AC'],
        eligibility: '10th Pass. Centralized admission process.',
        imageUrl: 'https://picsum.photos/seed/itimumbai/600/400',
        about: 'Located in the heart of Mumbai, providing skilled workforce to the industrial capital of India.',
        level: 'after_10th',
        fee: 'Rs. 3,000 - Rs. 5,000 per year',
        scholarships: 'Government stipend available.',
        latitude: 18.9828,
        longitude: 72.8347,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9828,72.8347',
        contactInfo: {
            phone: '+91-22-2309-6918',
            email: 'iti.mumbai@dvet.gov.in',
            website: 'https://www.dvet.gov.in',
            address: '374, Sane Guruji Marg, Agripada, Mumbai 400011'
        },
        hostelAvailable: false,
        hostelFees: 'N/A',
        mediumOfInstruction: ['Marathi', 'English'],
        establishedYear: 1962,
        affiliation: 'NCVT',
        placementRate: 75
    },
    {
        id: 'govt-iti-pusa',
        name: 'Government ITI, Pusa',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Electronics Mechanic', 'Surveyor', 'Plumber'],
        eligibility: '10th Pass. Admission via Delhi ITI Online Admission.',
        imageUrl: 'https://picsum.photos/seed/itipusa/600/400',
        about: 'A leading ITI in North India with modern workshops and strong industry tie-ups.',
        level: 'after_10th',
        fee: 'Rs. 2,500 per year',
        scholarships: 'Fee concession and scholarships for Delhi residents.',
        latitude: 28.6349,
        longitude: 77.1663,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6349,77.1663',
        contactInfo: {
            phone: '+91-11-2584-1234',
            email: 'itipusa@nic.in',
            website: 'https://itidelhi.admissions.nic.in',
            address: 'Pusa Campus, New Delhi 110012'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 3,000 per year',
        mediumOfInstruction: ['Hindi', 'English'],
        establishedYear: 1965,
        affiliation: 'NCVT',
        placementRate: 85
    },
    {
        id: 'govt-iti-bangalore',
        name: 'Government ITI (Dairy Circle), Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Turner', 'Machinist', 'Welder'],
        eligibility: '10th Pass. Merit-based admission.',
        imageUrl: 'https://picsum.photos/seed/itibangalore/600/400',
        about: 'The most prominent ITI in Bangalore, known for its rigorous training and placement in tech and manufacturing sectors.',
        level: 'after_10th',
        fee: 'Rs. 2,000 - Rs. 4,000 per year',
        scholarships: 'Vidyasiri and other state scholarships.',
        latitude: 12.9352,
        longitude: 77.6060,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9352,77.6060',
        contactInfo: {
            phone: '+91-80-2295-5555',
            email: 'principal.itidairy@karnataka.gov.in',
            website: 'https://emp.kar.nic.in',
            address: 'Dairy Circle, Hosur Road, Bangalore 560029'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 2,500 per year',
        mediumOfInstruction: ['Kannada', 'English'],
        establishedYear: 1955,
        affiliation: 'NCVT',
        placementRate: 88
    },
    {
        id: 'govt-iti-hyderabad',
        name: 'Government ITI, Mallepally',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Government',
        courses: ['Electrician', 'Fitter', 'Diesel Mechanic', 'R&AC', 'Draughtsman Civil'],
        eligibility: '10th Pass. Admission via TS ITI Online.',
        imageUrl: 'https://picsum.photos/seed/itihyderabad/600/400',
        about: 'Oldest and largest ITI in Telangana, offering quality vocational training.',
        level: 'after_10th',
        fee: 'Rs. 3,000 per year',
        scholarships: 'State government scholarships available.',
        latitude: 17.3904,
        longitude: 78.4632,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.3904,78.4632',
        contactInfo: {
            phone: '+91-40-2334-5678',
            email: 'iti.mallepally@telangana.gov.in',
            website: 'https://iti.telangana.gov.in',
            address: 'Mallepally, Hyderabad 500057'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 3,000 per year',
        mediumOfInstruction: ['Telugu', 'English'],
        establishedYear: 1960,
        affiliation: 'NCVT',
        placementRate: 78
    },

    // ==================== ARTS & HUMANITIES COLLEGES ====================



    {
        id: 'presidency-kolkata',
        name: 'Presidency University, Kolkata',
        district: 'Kolkata',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.A. Bengali', 'B.A. English', 'B.A. History', 'B.A. Philosophy', 'B.A. Political Science'],
        eligibility: '10+2. Admission via PUBDET entrance exam.',
        imageUrl: 'https://picsum.photos/seed/presidency/600/400',
        about: 'One of the oldest and most prestigious institutions in India, offering high-quality education in liberal arts.',
        level: 'after_12th',
        fee: 'Rs. 4,000 - Rs. 6,000 per year',
        scholarships: 'Swami Vivekananda Merit-cum-Means Scholarship.',
        latitude: 22.5753,
        longitude: 88.3639,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.5753,88.3639',
        contactInfo: {
            phone: '+91-33-2241-1960',
            email: 'registrar@presiuniv.ac.in',
            website: 'https://www.presiuniv.ac.in',
            address: '86/1, College Street, Kolkata 700073'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1817,
        affiliation: 'State University',
        nirfRank: 45,
        placementRate: 50,
        averagePackage: '4.5 LPA'
    },


    // ==================== COMMERCE & MANAGEMENT COLLEGES ====================


    {
        id: 'goenka-kolkata',
        name: 'Goenka College of Commerce and Business Administration, Kolkata',
        district: 'Kolkata',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.Com (Hons)', 'M.Com', 'MBA'],
        eligibility: '10+2. Admission based on merit.',
        imageUrl: 'https://picsum.photos/seed/goenka/600/400',
        about: 'A heritage government college in Kolkata, exclusively for commerce education. Very affordable and high quality.',
        level: 'after_12th',
        fee: 'Rs. 2,000 - Rs. 4,000 per year',
        scholarships: 'Kanyashree and other state scholarships.',
        latitude: 22.5689,
        longitude: 88.3646,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.5689,88.3646',
        contactInfo: {
            phone: '+91-33-2241-2216',
            email: 'principal@goenkacollege.net',
            website: 'http://goenkacollege.net',
            address: '210, B.B. Ganguly Street, Kolkata 700012'
        },
        hostelAvailable: false,
        hostelFees: 'N/A',
        mediumOfInstruction: ['English'],
        establishedYear: 1905,
        affiliation: 'University of Calcutta',
        placementRate: 85,
        averagePackage: '5 LPA'
    },

    {
        id: 'hindu-college-delhi',
        name: 'Hindu College, New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.Com (Hons)', 'B.A. Economics (Hons)', 'B.Sc. Statistics'],
        eligibility: '10+2. Admission via CUET-UG.',
        imageUrl: 'https://picsum.photos/seed/hindu/600/400',
        about: 'One of the most prestigious colleges under Delhi University, known for its vibrant political and cultural life.',
        level: 'after_12th',
        fee: 'Rs. 18,000 - Rs. 22,000 per year',
        scholarships: 'Various government and college scholarships.',
        latitude: 28.6844,
        longitude: 77.2104,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6844,77.2104',
        contactInfo: {
            phone: '+91-11-2766-7184',
            email: 'principal@hinducollege.org',
            website: 'https://hinducollege.ac.in',
            address: 'University Enclave, Delhi 110007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1899,
        affiliation: 'University of Delhi',
        nirfRank: 2,
        placementRate: 90,
        averagePackage: '10 LPA'
    },

    // ==================== MEDICAL & NURSING COLLEGES ====================

    {
        id: 'kgmu-lucknow',
        name: 'King George\'s Medical University (KGMU), Lucknow',
        district: 'Lucknow',
        state: 'Uttar Pradesh',
        type: 'Government',
        courses: ['MBBS', 'BDS', 'B.Sc Nursing'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/kgmu/600/400',
        about: 'A historic medical university in North India, offering excellent clinical exposure and research opportunities.',
        level: 'after_12th',
        fee: 'Rs. 55,000 per year',
        scholarships: 'UP State Government scholarships.',
        latitude: 26.8693,
        longitude: 80.9150,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=26.8693,80.9150',
        contactInfo: {
            phone: '+91-522-225-7540',
            email: 'registrar@kgmcindia.edu',
            website: 'https://www.kgmu.org',
            address: 'Shah Mina Road, Chowk, Lucknow 226003'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1911,
        affiliation: 'Medical University',
        nirfRank: 12,
        placementRate: 100,
        averagePackage: '10 LPA'
    },
    {
        id: 'grant-medical-mumbai',
        name: 'Grant Medical College & Sir J.J. Group of Hospitals, Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['MBBS', 'B.Sc Nursing', 'BPMT'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/grantmedical/600/400',
        about: 'One of the oldest medical colleges in Asia, attached to the massive J.J. Hospital, providing unmatched clinical experience.',
        level: 'after_12th',
        fee: 'Rs. 1,10,000 per year',
        scholarships: 'State government scholarships for reserved categories.',
        latitude: 18.9633,
        longitude: 72.8333,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9633,72.8333',
        contactInfo: {
            phone: '+91-22-2373-5555',
            email: 'dean_gmcjjh@maha.gov.in',
            website: 'https://ggmcjjh.com',
            address: 'Byculla, Mumbai 400008'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 4,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1845,
        affiliation: 'MUHS Nashik',
        nirfRank: 15,
        placementRate: 100,
        averagePackage: '9 LPA'
    },
    {
        id: 'mmc-chennai',
        name: 'Madras Medical College (MMC), Chennai',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['MBBS', 'B.Pharm', 'B.Sc Nursing', 'BPT'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/mmc/600/400',
        about: 'The oldest medical college in India, attached to the Rajiv Gandhi Government General Hospital.',
        level: 'after_12th',
        fee: 'Rs. 13,600 per year',
        scholarships: 'TN State Government scholarships.',
        latitude: 13.0827,
        longitude: 80.2707,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0827,80.2707',
        contactInfo: {
            phone: '+91-44-2530-5000',
            email: 'deanmmc@tn.gov.in',
            website: 'http://www.mmc.ac.in',
            address: 'E.V.R Periyar Salai, Park Town, Chennai 600003'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1835,
        affiliation: 'MGR Medical University',
        nirfRank: 11,
        placementRate: 100,
        averagePackage: '10 LPA'
    },

    // ==================== PROFESSIONAL BODIES ====================
    {
        id: 'icai-delhi',
        name: 'The Institute of Chartered Accountants of India (ICAI)',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['CA Foundation', 'CA Intermediate', 'CA Final'],
        eligibility: '12th Pass (Foundation) / Graduate (Direct Entry).',
        imageUrl: 'https://www.icai.org/post/icai-bhawan-new-delhi',
        about: 'The statutory body established by an Act of Parliament for regulating the profession of Chartered Accountancy in India.',
        level: 'after_12th',
        fee: 'Rs. 9,000 - Rs. 18,000 (Registration Fees)',
        scholarships: 'ICAI Merit and Need-based Scholarships.',
        latitude: 28.6289,
        longitude: 77.2415,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6289,77.2415',
        contactInfo: {
            phone: '+91-11-3989-3989',
            email: 'icaiho@icai.in',
            website: 'https://www.icai.org',
            address: 'ICAI Bhawan, Indraprastha Marg, New Delhi 110002'
        },
        hostelAvailable: false,
        hostelFees: 'N/A',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1949,
        affiliation: 'Parliament Act',
        placementRate: 98,
        averagePackage: '9 LPA'
    },

    // ==================== TOP ENGINEERING COLLEGES (GOVT) ====================
    {
        id: 'iit-bombay',
        name: 'IIT Bombay',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech Electrical', 'B.Tech Mechanical'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitbombay/600/400',
        about: 'Internationally acclaimed for excellence in research and engineering education.',
        level: 'after_12th',
        fee: 'Rs. 2,00,000 per year',
        scholarships: 'Full aid for SC/ST and income-based waivers.',
        latitude: 19.1334,
        longitude: 72.9133,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=19.1334,72.9133',
        contactInfo: {
            phone: '+91-22-2572-2545',
            email: 'pro@iitb.ac.in',
            website: 'https://www.iitb.ac.in',
            address: 'Powai, Mumbai 400076'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1958,
        affiliation: 'IIT',
        nirfRank: 3,
        placementRate: 95,
        averagePackage: '25 LPA'
    },
    {
        id: 'iit-delhi',
        name: 'IIT Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech Mathematics & Computing', 'B.Tech Electrical'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitdelhi/600/400',
        about: 'A center of excellence for training, research and development in science, engineering and technology.',
        level: 'after_12th',
        fee: 'Rs. 2,00,000 per year',
        scholarships: 'Various government and alumni scholarships.',
        latitude: 28.5450,
        longitude: 77.1926,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5450,77.1926',
        contactInfo: {
            phone: '+91-11-2659-1999',
            email: 'webmaster@admin.iitd.ac.in',
            website: 'https://home.iitd.ac.in',
            address: 'Hauz Khas, New Delhi 110016'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1961,
        affiliation: 'IIT',
        nirfRank: 2,
        placementRate: 96,
        averagePackage: '24 LPA'
    },
    {
        id: 'iit-madras',
        name: 'IIT Madras',
        district: 'Chennai',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech Aerospace', 'B.Tech Civil'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitmadras/600/400',
        about: 'Consistently ranked #1 in NIRF Engineering for several years.',
        level: 'after_12th',
        fee: 'Rs. 2,00,000 per year',
        scholarships: 'Full tuition waiver for eligible students.',
        latitude: 12.9915,
        longitude: 80.2337,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9915,80.2337',
        contactInfo: {
            phone: '+91-44-2257-8000',
            email: 'registrar@iitm.ac.in',
            website: 'https://www.iitm.ac.in',
            address: 'IIT P.O., Chennai 600036'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1959,
        affiliation: 'IIT',
        nirfRank: 1,
        placementRate: 92,
        averagePackage: '22 LPA'
    },
    {
        id: 'iit-kharagpur',
        name: 'IIT Kharagpur',
        district: 'Kharagpur',
        state: 'West Bengal',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Arch', 'B.Tech Law (LLB'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitkgp/600/400',
        about: 'The first IIT to be established, offering the widest range of courses.',
        level: 'after_12th',
        fee: 'Rs. 2,00,000 per year',
        scholarships: 'Scholarships for SC/ST/PwD.',
        latitude: 22.3149,
        longitude: 87.3105,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.3149,87.3105',
        contactInfo: {
            phone: '+91-3222-282-022',
            email: 'registrar@iitkgp.ac.in',
            website: 'http://www.iitkgp.ac.in',
            address: 'Kharagpur, West Bengal 721302'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1951,
        affiliation: 'IIT',
        nirfRank: 6,
        placementRate: 90,
        averagePackage: '20 LPA'
    },
    {
        id: 'iit-roorkee',
        name: 'IIT Roorkee',
        district: 'Roorkee',
        state: 'Uttarakhand',
        type: 'Government',
        courses: ['B.Tech Civil', 'B.Arch', 'B.Tech Mechanical'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iitroorkee/600/400',
        about: 'Oldest technical institution in Asia, renowned for Civil Engineering and Architecture.',
        level: 'after_12th',
        fee: 'Rs. 2,00,000 per year',
        scholarships: 'Merit-cum-means scholarships.',
        latitude: 29.8644,
        longitude: 77.8964,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=29.8644,77.8964',
        contactInfo: {
            phone: '+91-1332-285-311',
            email: 'registrar@iitr.ac.in',
            website: 'https://www.iitr.ac.in',
            address: 'Roorkee, Uttarakhand 247667'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 20,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1847,
        affiliation: 'IIT',
        nirfRank: 5,
        placementRate: 88,
        averagePackage: '18 LPA'
    },
    {
        id: 'nit-trichy',
        name: 'NIT Trichy',
        district: 'Tiruchirappalli',
        state: 'Tamil Nadu',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Mechanical'],
        eligibility: '10+2 with PCM. Admission via JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nittrichy/600/400',
        about: 'Top-ranked NIT in India, known for excellent technical education and campus life.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Central government scholarships.',
        latitude: 10.7626,
        longitude: 78.8139,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=10.7626,78.8139',
        contactInfo: {
            phone: '+91-431-250-3000',
            email: 'director@nitt.edu',
            website: 'https://www.nitt.edu',
            address: 'Tanjore Main Road, Tiruchirappalli 620015'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1964,
        affiliation: 'NIT',
        nirfRank: 9,
        placementRate: 94,
        averagePackage: '15 LPA'
    },
    {
        id: 'nit-surathkal',
        name: 'NIT Surathkal',
        district: 'Surathkal',
        state: 'Karnataka',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech IT', 'B.Tech Mining'],
        eligibility: '10+2 with PCM. Admission via JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitsurathkal/600/400',
        about: 'One of the few NITs with a private beach, known for strong industry connections.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Fee remission for economically weaker sections.',
        latitude: 13.0119,
        longitude: 74.7943,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=13.0119,74.7943',
        contactInfo: {
            phone: '+91-824-247-4000',
            email: 'registrar@nitk.ac.in',
            website: 'https://www.nitk.ac.in',
            address: 'NH 66, Srinivasnagar, Surathkal 575025'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 25,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'NIT',
        nirfRank: 12,
        placementRate: 92,
        averagePackage: '14 LPA'
    },
    {
        id: 'nit-warangal',
        name: 'NIT Warangal',
        district: 'Warangal',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech ECE', 'B.Tech Biotechnology'],
        eligibility: '10+2 with PCM. Admission via JEE Main.',
        imageUrl: 'https://picsum.photos/seed/nitwarangal/600/400',
        about: 'First NIT to be established (formerly RECW), known for research outputs.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'State and central scholarships.',
        latitude: 17.9835,
        longitude: 79.5298,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.9835,79.5298',
        contactInfo: {
            phone: '+91-870-245-9191',
            email: 'director@nitw.ac.in',
            website: 'https://www.nitw.ac.in',
            address: 'Warangal, Telangana 506004'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 28,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1959,
        affiliation: 'NIT',
        nirfRank: 21,
        placementRate: 90,
        averagePackage: '13.5 LPA'
    },
    {
        id: 'vnit-nagpur',
        name: 'VNIT Nagpur',
        district: 'Nagpur',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['B.Tech Mining', 'B.Tech Metallurgical', 'B.Arch'],
        eligibility: '10+2 with PCM. Admission via JEE Main.',
        imageUrl: 'https://picsum.photos/seed/vnitnagpur/600/400',
        about: 'Leading technology institute in Central India.',
        level: 'after_12th',
        fee: 'Rs. 1,25,000 per year',
        scholarships: 'Maharashtra state scholarships.',
        latitude: 21.1230,
        longitude: 79.0526,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=21.1230,79.0526',
        contactInfo: {
            phone: '+91-712-222-2828',
            email: 'registrar@vnit.ac.in',
            website: 'https://vnit.ac.in',
            address: 'South Ambazari Road, Nagpur 440010'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 22,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1960,
        affiliation: 'NIT',
        nirfRank: 41,
        placementRate: 85,
        averagePackage: '10 LPA'
    },
    {
        id: 'iit-hyderabad',
        name: 'IIT Hyderabad',
        district: 'Sangareddy',
        state: 'Telangana',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech AI', 'B.Des'],
        eligibility: '10+2 with PCM. Admission via JEE Advanced.',
        imageUrl: 'https://picsum.photos/seed/iithyderabad/600/400',
        about: 'One of the fastest growing new IITs, with a strong focus on AI and Design.',
        level: 'after_12th',
        fee: 'Rs. 2,00,000 per year',
        scholarships: 'Merit-cum-Means scholarships.',
        latitude: 17.5947,
        longitude: 78.1197,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.5947,78.1197',
        contactInfo: {
            phone: '+91-40-2301-6033',
            email: 'office.acad@iith.ac.in',
            website: 'https://www.iith.ac.in',
            address: 'Kandi, Sangareddy 502285'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 2008,
        affiliation: 'IIT',
        nirfRank: 8,
        placementRate: 88,
        averagePackage: '20 LPA'
    },
    {
        id: 'dtu-delhi',
        name: 'DTU',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.Tech CSE', 'B.Tech Software', 'B.Tech Biotechnology'],
        eligibility: '10+2 with PCM. Admission via JAC Delhi (JEE Main).',
        imageUrl: 'https://picsum.photos/seed/dtu/600/400',
        about: 'Formerly DCE, one of the oldest and best engineering colleges in Delhi.',
        level: 'after_12th',
        fee: 'Rs. 1,66,000 per year',
        scholarships: 'Delhi Government scholarships.',
        latitude: 28.7499,
        longitude: 77.1170,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.7499,77.1170',
        contactInfo: {
            phone: '+91-11-2787-1018',
            email: 'registrar@dtu.ac.in',
            website: 'http://www.dtu.ac.in',
            address: 'Shahbad Daulatpur, Bawana Road, Delhi 110042'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 50,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1941,
        affiliation: 'State University',
        nirfRank: 29,
        placementRate: 98,
        averagePackage: '15 LPA'
    },

    // ==================== TOP MEDICAL COLLEGES (GOVT) ====================
    {
        id: 'aiims-delhi',
        name: 'AIIMS Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['MBBS', 'B.Sc. Nursing', 'B.Optom'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/aiimsdelhi/600/400',
        about: 'The most prestigious medical institute in India.',
        level: 'after_12th',
        fee: 'Rs. 1,628 (Total Annual Fee)',
        scholarships: 'Merit scholarships available.',
        latitude: 28.5672,
        longitude: 77.2100,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5672,77.2100',
        contactInfo: {
            phone: '+91-11-2658-8500',
            email: 'director@aiims.edu',
            website: 'https://www.aiims.edu',
            address: 'Ansari Nagar, New Delhi 110029'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 1,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1956,
        affiliation: 'Autonomous (INI)',
        nirfRank: 1,
        placementRate: 100,
        averagePackage: '12 LPA'
    },
    {
        id: 'jipmer-puducherry',
        name: 'JIPMER',
        district: 'Puducherry',
        state: 'Puducherry',
        type: 'Government',
        courses: ['MBBS', 'B.Sc. Nursing', 'B.Sc. Allied Health'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/jipmer/600/400',
        about: 'Institute of National Importance under Ministry of Health.',
        level: 'after_12th',
        fee: 'Rs. 12,000 per year',
        scholarships: 'National scholarships.',
        latitude: 11.9542,
        longitude: 79.8037,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=11.9542,79.8037',
        contactInfo: {
            phone: '+91-413-229-6002',
            email: 'director@jipmer.edu.in',
            website: 'https://jipmer.edu.in',
            address: 'Jipmer Campus Rd, Gorimedu, Puducherry 605006'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 6,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1823,
        affiliation: 'Autonomous (INI)',
        nirfRank: 5,
        placementRate: 100,
        averagePackage: '10 LPA'
    },
    {
        id: 'gmc-chandigarh',
        name: 'GMC Chandigarh',
        district: 'Chandigarh',
        state: 'Chandigarh',
        type: 'Government',
        courses: ['MBBS', 'B.Sc. Nursing'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/gmcchandigarh/600/400',
        about: 'Consistently ranked among top 10 government medical colleges.',
        level: 'after_12th',
        fee: 'Rs. 25,000 per year',
        scholarships: 'UT scholarships.',
        latitude: 30.7180,
        longitude: 76.7725,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=30.7180,76.7725',
        contactInfo: {
            phone: '+91-172-260-1023',
            email: 'dpgmch_chd@gmch.gov.in',
            website: 'https://gmch.gov.in',
            address: 'Sector 32, Chandigarh 160030'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 8,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1991,
        affiliation: 'Panjab University',
        nirfRank: 25,
        placementRate: 100,
        averagePackage: '9 LPA'
    },
    {
        id: 'maulana-azad-dental',
        name: 'Maulana Azad Dental College',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['BDS', 'MDS'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/madc/600/400',
        about: 'Premier dental and medical institute in India.',
        level: 'after_12th',
        fee: 'Rs. 3,000 per year',
        scholarships: 'Delhi Government scholarships.',
        latitude: 28.6366,
        longitude: 77.2411,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6366,77.2411',
        contactInfo: {
            phone: '+91-11-2323-3925',
            email: 'registrar@mamc.ac.in',
            website: 'https://mamc.ac.in',
            address: 'Bahadur Shah Zafar Marg, New Delhi 110002'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 5,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1983,
        affiliation: 'Delhi University',
        nirfRank: 4,
        placementRate: 90,
        averagePackage: '8 LPA'
    },
    {
        id: 'gdc-mumbai',
        name: 'GDC Mumbai',
        district: 'Mumbai',
        state: 'Maharashtra',
        type: 'Government',
        courses: ['BDS', 'MDS'],
        eligibility: '10+2 with PCB. Admission via NEET-UG.',
        imageUrl: 'https://picsum.photos/seed/gdcmumbai/600/400',
        about: 'Top dental college in Maharashtra located in St. George Hospital campus.',
        level: 'after_12th',
        fee: 'Rs. 60,000 per year',
        scholarships: 'State government scholarships.',
        latitude: 18.9407,
        longitude: 72.8368,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=18.9407,72.8368',
        contactInfo: {
            phone: '+91-22-2262-0668',
            email: 'dean@gdcmumbai.org',
            website: 'https://www.gdcmumbai.org',
            address: 'St George Hospital, Fort, Mumbai 400001'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 10,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1938,
        affiliation: 'MUHS Nashik',
        nirfRank: 15,
        placementRate: 85,
        averagePackage: '6 LPA'
    },

    // ==================== COMMERCE & MANAGEMENT (GOVT) ====================
    {
        id: 'srcc-delhi',
        name: 'SRCC Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.Com (Hons)', 'B.A. Economics (Hons)'],
        eligibility: '10+2. Admission via CUET-UG.',
        imageUrl: 'https://picsum.photos/seed/srcc/600/400',
        about: 'Best Commerce college in India.',
        level: 'after_12th',
        fee: 'Rs. 30,000 per year',
        scholarships: 'Scholarships for needy students.',
        latitude: 28.6908,
        longitude: 77.2104,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6908,77.2104',
        contactInfo: {
            phone: '+91-11-2766-7905',
            email: 'adminoffice@srcc.du.ac.in',
            website: 'https://www.srcc.edu',
            address: 'University Enclave, Delhi 110007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 50,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1926,
        affiliation: 'University of Delhi',
        nirfRank: 11,
        placementRate: 98,
        averagePackage: '12 LPA'
    },
    {
        id: 'shaheed-sukhdev',
        name: 'Shaheed Sukhdev College',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['BBA (FIA)', 'BMS', 'B.Sc. Computer Science'],
        eligibility: '10+2. Admission via CUET-UG.',
        imageUrl: 'https://picsum.photos/seed/sscbs/600/400',
        about: 'Best college for undergraduate management studies in Asia.',
        level: 'after_12th',
        fee: 'Rs. 25,000 per year',
        scholarships: 'Financial aid availble.',
        latitude: 28.7328,
        longitude: 77.1188,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.7328,77.1188',
        contactInfo: {
            phone: '+91-11-2757-3447',
            email: 'principal@sscbsdu.ac.in',
            website: 'https://sscbs.du.ac.in',
            address: 'Dr. KN Katju Marg, Rohini Sector 16, Delhi 110089'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1987,
        affiliation: 'University of Delhi',
        nirfRank: 92,
        placementRate: 95,
        averagePackage: '10 LPA'
    },
    {
        id: 'iim-indore-ipm',
        name: 'IIM Indore (IPM)',
        district: 'Indore',
        state: 'Madhya Pradesh',
        type: 'Government',
        courses: ['IPM (Integrated Programme in Management)'],
        eligibility: '10+2. Admission via IPMAT.',
        imageUrl: 'https://picsum.photos/seed/iimindore/600/400',
        about: '5-Year Integrated BBA+MBA program straight after 12th.',
        level: 'after_12th',
        fee: 'Rs. 4,00,000 per year',
        scholarships: 'NBFA scholarships.',
        latitude: 22.6288,
        longitude: 75.8037,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=22.6288,75.8037',
        contactInfo: {
            phone: '+91-731-243-9666',
            email: 'ipm@iimidr.ac.in',
            website: 'https://www.iimidr.ac.in',
            address: 'Prabandh Shikhar, Rau-Pithampur Road, Indore 453556'
        },
        hostelAvailable: true,
        hostelFees: 'Inclusive',
        mediumOfInstruction: ['English'],
        establishedYear: 1996,
        affiliation: 'IIM',
        nirfRank: 8,
        placementRate: 100,
        averagePackage: '25 LPA'
    },
    {
        id: 'iim-rohtak-ipm',
        name: 'IIM Rohtak (IPM)',
        district: 'Rohtak',
        state: 'Haryana',
        type: 'Government',
        courses: ['IPM (Integrated Programme in Management)'],
        eligibility: '10+2. Admission via IPMAT.',
        imageUrl: 'https://picsum.photos/seed/iimrohtak/600/400',
        about: 'IIM Rohtak BBA+MBA integrated course.',
        level: 'after_12th',
        fee: 'Rs. 3,50,000 per year',
        scholarships: 'IIM scholarships.',
        latitude: 28.8753,
        longitude: 76.5594,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.8753,76.5594',
        contactInfo: {
            phone: '+91-1262-228-555',
            email: 'ipm.outreach@iimrohtak.ac.in',
            website: 'https://www.iimrohtak.ac.in',
            address: 'Management City, Sunaria, Rohtak 124010'
        },
        hostelAvailable: true,
        hostelFees: 'Inclusive',
        mediumOfInstruction: ['English'],
        establishedYear: 2010,
        affiliation: 'IIM',
        nirfRank: 12,
        placementRate: 100,
        averagePackage: '18 LPA'
    },

    // ==================== ARTS & HUMANITIES (GOVT) ====================
    {
        id: 'st-stephens-delhi',
        name: 'St. Stephen\'s College',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government-Aided',
        courses: ['B.A. Economics', 'B.A. English', 'B.A. History', 'B.Sc. Physics'],
        eligibility: '10+2. Admission via CUET + Interview.',
        imageUrl: 'https://picsum.photos/seed/ststephens/600/400',
        about: 'Oldest college in Delhi, highly exclusive and prestigious.',
        level: 'after_12th',
        fee: 'Rs. 40,000 per year',
        scholarships: 'Extensive financial aid.',
        latitude: 28.6859,
        longitude: 77.2135,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6859,77.2135',
        contactInfo: {
            phone: '+91-11-2766-7200',
            email: 'principal@ststephens.edu',
            website: 'https://www.ststephens.edu',
            address: 'University Enclave, Delhi 110007'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1881,
        affiliation: 'University of Delhi',
        nirfRank: 14,
        placementRate: 85,
        averagePackage: '9 LPA'
    },
    {
        id: 'lsr-delhi',
        name: 'Lady Shri Ram College',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government-Aided',
        courses: ['B.A. Psychology', 'B.A. Journalism', 'B.A. Political Science'],
        eligibility: '10+2. Admission via CUET-UG.',
        imageUrl: 'https://picsum.photos/seed/lsr/600/400',
        about: 'Premier college for women, excellent for Humanities and Social Sciences.',
        level: 'after_12th',
        fee: 'Rs. 16,000 per year',
        scholarships: 'College financial aid.',
        latitude: 28.5562,
        longitude: 77.2407,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5562,77.2407',
        contactInfo: {
            phone: '+91-11-2643-4459',
            email: 'principal@lsr.edu.in',
            website: 'https://lsr.edu.in',
            address: 'Lajpat Nagar IV, New Delhi 110024'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 60,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1956,
        affiliation: 'University of Delhi',
        nirfRank: 9,
        placementRate: 90,
        averagePackage: '8 LPA'
    },
    {
        id: 'jamia-millia',
        name: 'Jamia Millia Islamia',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['B.A. Mass Media', 'B.A. Sociology', 'B.Tech'],
        eligibility: '10+2. Admission via JMI Entrance / CUET.',
        imageUrl: 'https://picsum.photos/seed/jmi/600/400',
        about: 'Central University known for Mass Communication and research.',
        level: 'after_12th',
        fee: 'Rs. 7,000 - Rs. 15,000 per year',
        scholarships: 'JMI scholarships.',
        latitude: 28.5616,
        longitude: 77.2802,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5616,77.2802',
        contactInfo: {
            phone: '+91-11-2698-1717',
            email: 'registrar@jmi.ac.in',
            website: 'https://www.jmi.ac.in',
            address: 'Jamia Nagar, New Delhi 110025'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English', 'Urdu', 'Hindi'],
        establishedYear: 1920,
        affiliation: 'Central University',
        nirfRank: 3,
        placementRate: 75,
        averagePackage: '7 LPA'
    },
    {
        id: 'iimc-delhi',
        name: 'IIMC New Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['PG Diploma in Journalism', 'PG Diploma in Advertising & PR'],
        eligibility: 'Graduate. Admission via IIMC Entrance/CUET-PG.',
        imageUrl: 'https://picsum.photos/seed/iimc/600/400',
        about: 'Premier institute for journalism and mass communication training.',
        level: 'after_12th',
        fee: 'Rs. 50,000 - Rs. 90,000 per year',
        scholarships: 'Freeships available.',
        latitude: 28.5417,
        longitude: 77.1691,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.5417,77.1691',
        contactInfo: {
            phone: '+91-11-2674-2920',
            email: 'academic@iimc.gov.in',
            website: 'http://iimc.nic.in',
            address: 'Aruna Asaf Ali Marg, New Delhi 110067'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English', 'Hindi'],
        establishedYear: 1965,
        affiliation: 'Ministry of I&B',
        placementRate: 90,
        averagePackage: '6.5 LPA'
    },

    // ==================== LAW (GOVT) ====================
    {
        id: 'nlu-delhi',
        name: 'NLU Delhi',
        district: 'New Delhi',
        state: 'Delhi',
        type: 'Government',
        courses: ['BA LLB (Hons)'],
        eligibility: '10+2. Admission via AILET.',
        imageUrl: 'https://picsum.photos/seed/nludelhi/600/400',
        about: 'One of the elite National Law Universities in India.',
        level: 'after_12th',
        fee: 'Rs. 1,80,000 per year',
        scholarships: 'Need-cum-merit aid.',
        latitude: 28.6044,
        longitude: 77.0267,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=28.6044,77.0267',
        contactInfo: {
            phone: '+91-11-2803-4257',
            email: 'info@nludelhi.ac.in',
            website: 'https://nludelhi.ac.in',
            address: 'Sector 14, Dwarka, New Delhi 110078'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 2008,
        affiliation: 'NLU',
        nirfRank: 2,
        placementRate: 100,
        averagePackage: '16 LPA'
    },
    {
        id: 'nlsiu-bangalore',
        name: 'NLSIU Bangalore',
        district: 'Bengaluru',
        state: 'Karnataka',
        type: 'Government',
        courses: ['BA LLB (Hons)'],
        eligibility: '10+2. Admission via CLAT.',
        imageUrl: 'https://picsum.photos/seed/nlsiu/600/400',
        about: 'The first National Law University of India, frequently ranked #1.',
        level: 'after_12th',
        fee: 'Rs. 2,50,000 per year',
        scholarships: 'Scholarships for needy students.',
        latitude: 12.9691,
        longitude: 77.5098,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=12.9691,77.5098',
        contactInfo: {
            phone: '+91-80-2321-3160',
            email: 'registrar@nls.ac.in',
            website: 'https://www.nls.ac.in',
            address: 'Nagarbhavi, Bangalore 560072'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 40,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1986,
        affiliation: 'NLU',
        nirfRank: 1,
        placementRate: 100,
        averagePackage: '18 LPA'
    },
    {
        id: 'nalsar-hyderabad',
        name: 'NALSAR Hyderabad',
        district: 'Hyderabad',
        state: 'Telangana',
        type: 'Government',
        courses: ['BA LLB (Hons)'],
        eligibility: '10+2. Admission via CLAT.',
        imageUrl: 'https://picsum.photos/seed/nalsar/600/400',
        about: 'Top tier law school known for its rigorous academic curriculum.',
        level: 'after_12th',
        fee: 'Rs. 2,20,000 per year',
        scholarships: 'State government reimbursement available.',
        latitude: 17.6534,
        longitude: 78.5492,
        googleMapsUrl: 'https://www.google.com/maps/search/?api=1&query=17.6534,78.5492',
        contactInfo: {
            phone: '+91-40-2349-8105',
            email: 'registrar@nalsar.ac.in',
            website: 'https://www.nalsar.ac.in',
            address: 'Justice City, Shameerpet, Hyderabad 500101'
        },
        hostelAvailable: true,
        hostelFees: 'Rs. 30,000 per year',
        mediumOfInstruction: ['English'],
        establishedYear: 1998,
        affiliation: 'NLU',
        nirfRank: 3,
        placementRate: 98,
        averagePackage: '15 LPA'
    }
];

/**
 * TEMPLATE FOR ADDING NEW COLLEGES:
 * 
 * {
 *     id: 'unique-id-kebab-case', // e.g., 'delhi-univ'
 *     name: 'Official College Name',
 *     district: 'District Name',
 *     state: 'State Name',
 *     type: 'Government' | 'Private' | 'Public-Private',
 *     courses: ['Course 1', 'Course 2', ...], // Array of course names
 *     eligibility: 'Eligibility criteria with admission process',
 *     imageUrl: 'https://picsum.photos/seed/uniqueseed/600/400', // Or real image URL
 *     about: 'Brief description of the college in 1-2 sentences',
 *     level: 'after_10th' | 'after_12th',
 *     fee: 'Rs. X,XXX - Rs. X,XXX per year',
 *     scholarships: 'Description of available scholarships',
 *     latitude: 00.0000, // Get from Google Maps
 *     longitude: 00.0000, // Get from Google Maps
 *     contactInfo: {
 *         phone: '+91-XXX-XXX-XXXX',
 *         email: 'email@college.ac.in',
 *         website: 'https://www.college.ac.in',
 *         address: 'Full postal address'
 *     },
 *     hostelAvailable: true | false,
 *     hostelFees: 'Rs. X,XXX - Rs. X,XXX per year', // Optional
 *     mediumOfInstruction: ['English', 'Hindi', ...], // Array of languages
 *     establishedYear: YYYY, // Optional
 *     affiliation: 'University/Board name', // Optional
 *     nirfRank: XX, // Optional, only if ranked
 *     placementRate: 0-100, // Optional, percentage
 *     averagePackage: 'X LPA' // Optional
 * },
 */
