import type { Resource } from './types';

export const resources: Resource[] = [
  // ==================== CLASS 10 RESOURCES ====================
  // Career Guidance & Stream Selection
  {
    id: 1,
    title: 'Career360 - Stream Selection Guide',
    description: 'Comprehensive guide to help Class 10 students choose the right stream (Science, Commerce, Arts) based on interests and career goals.',
    category: 'Career Guidance',
    link: 'https://www.careers360.com/courses-after-10th',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎯',
    tags: ['Stream Selection', 'Career Counseling', 'Class 10'],
    state: 'All India'
  },
  {
    id: 2,
    title: 'Mindler - AI Career Assessment',
    description: 'AI-powered career assessment and personalized counseling for Class 10 students to discover their ideal stream and career path.',
    category: 'Career Guidance',
    link: 'https://www.mindler.com/',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: true,
    resourceType: 'Platform',
    icon: '🤖',
    tags: ['Career Assessment', 'AI', 'Psychometric Test'],
    state: 'All India'
  },

  // Board Exam Preparation
  {
    id: 3,
    title: 'NCERT Books & Solutions',
    description: 'Official NCERT textbooks and comprehensive solutions for all subjects. Free download available for Class 10 students.',
    category: 'E-Books',
    link: 'https://ncert.nic.in/textbook.php',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '📚',
    tags: ['NCERT', 'Textbooks', 'Board Exam', 'Free'],
    state: 'All India'
  },
  {
    id: 4,
    title: 'Diksha Portal by NCERT',
    description: 'National digital learning platform with video lessons, interactive content, and practice questions for CBSE Class 10.',
    category: 'Online Learning',
    link: 'https://diksha.gov.in/',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '🎓',
    tags: ['Video Lessons', 'CBSE', 'Free', 'Government'],
    state: 'All India'
  },
  {
    id: 5,
    title: 'Khan Academy (Hindi)',
    description: 'Free video lectures in Hindi for Maths and Science covering full Class 10 syllabus with practice exercises.',
    category: 'Online Learning',
    link: 'https://www.khanacademy.org/',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🌐',
    tags: ['Video Lectures', 'Maths', 'Science', 'Hindi', 'Free'],
    state: 'All India'
  },

  // YouTube Channels - Class 10
  {
    id: 6,
    title: 'Magnet Brains - Class 10 Complete Course',
    description: 'Complete CBSE Class 10 course in Hindi with animations and detailed explanations. 2M+ subscribers.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@MagnetBrainsEducation',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['CBSE', 'Hindi', 'Animated', 'Complete Course'],
    state: 'All India'
  },
  {
    id: 7,
    title: 'Vedantu Class 10',
    description: 'Live and recorded classes for Class 10 CBSE with master teachers. Includes board exam preparation strategies.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@VedantuClass910',
    targetClass: '10th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['Live Classes', 'CBSE', 'Board Exam'],
    state: 'All India'
  },

  // ==================== CLASS 12 - SCIENCE (PCM) ====================
  // Engineering Entrance Exams
  {
    id: 8,
    title: 'JEE Main Official Website (NTA)',
    description: 'Official National Testing Agency portal for JEE Main registration, syllabus, mock tests, and previous year papers.',
    category: 'Entrance Exams',
    link: 'https://jeemain.nta.nic.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏛️',
    tags: ['JEE Main', 'Engineering', 'NTA', 'Mock Tests'],
    state: 'All India'
  },
  {
    id: 9,
    title: 'JEE Advanced Official Portal',
    description: 'Official IIT portal for JEE Advanced exam, syllabus, past papers, and admission information for IITs.',
    category: 'Entrance Exams',
    link: 'https://jeeadv.ac.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎓',
    tags: ['JEE Advanced', 'IIT', 'Engineering'],
    state: 'All India'
  },
  {
    id: 10,
    title: 'TS EAMCET Information',
    description: 'Official Telangana State Engineering, Agriculture & Medical Common Entrance Test portal with syllabus and previous papers.',
    category: 'Entrance Exams',
    link: 'https://eamcet.tsche.ac.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '📋',
    tags: ['EAMCET', 'Telangana', 'State Exam'],
    state: 'Telangana'
  },
  {
    id: 11,
    title: 'AP EAPCET Portal',
    description: 'Andhra Pradesh Engineering, Agriculture & Pharmacy Common Entrance Test - official registration and preparation material.',
    category: 'Entrance Exams',
    link: 'https://apeapcet.nic.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '📋',
    tags: ['EAPCET', 'Andhra Pradesh', 'State Exam'],
    state: 'Andhra Pradesh'
  },
  {
    id: 12,
    title: 'MHT CET (Maharashtra)',
    description: 'Maharashtra Common Entrance Test for engineering and pharmacy admissions. Syllabus and mock tests available.',
    category: 'Entrance Exams',
    link: 'https://cetcell.mahacet.org/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '📋',
    tags: ['MHT CET', 'Maharashtra', 'State Exam'],
    state: 'Maharashtra'
  },

  // JEE Preparation - YouTube
  {
    id: 13,
    title: 'Physics Wallah - JEE/NEET',
    description: 'Most popular free JEE & NEET preparation channel with Alakh Pandey. Complete syllabus coverage in Hindi.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@PhysicsWallah',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['JEE', 'NEET', 'Free', 'Hindi', 'Complete Course'],
    state: 'All India'
  },
  {
    id: 14,
    title: 'Unacademy JEE',
    description: 'Premium JEE preparation with top educators. Free and paid courses available. Live classes and doubt solving.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@UnacademyJEE',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: true,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['JEE', 'Live Classes', 'Premium'],
    state: 'All India'
  },
  {
    id: 15,
    title: 'Mohit Tyagi - JEE Maths',
    description: 'Best Mathematics preparation for JEE Advanced. Deep concept building and problem-solving techniques.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@MohitTyagi',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['JEE', 'Mathematics', 'Free', 'Advanced'],
    state: 'All India'
  },

  // JEE Telegram Groups
  {
    id: 16,
    title: 'JEE Mains & Advanced Study Material',
    description: 'Daily questions, PDFs, mock tests, and previous year papers shared by IITians. 50K+ members.',
    category: 'Online Learning',
    link: 'https://t.me/jeemainadvanced',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Telegram',
    icon: '💬',
    tags: ['JEE', 'Study Material', 'Community'],
    state: 'All India'
  },

  // ==================== CLASS 12 - SCIENCE (PCB) ====================
  // Medical Entrance Exams
  {
    id: 17,
    title: 'NEET Official Website (NTA)',
    description: 'National Eligibility cum Entrance Test for medical admissions. Official syllabus, pattern, and mock tests.',
    category: 'Entrance Exams',
    link: 'https://neet.nta.nic.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '⚕️',
    tags: ['NEET', 'Medical', 'MBBS', 'NTA'],
    state: 'All India'
  },
  {
    id: 18,
    title: 'AIIMS Previous Year Papers',
    description: 'Archive of AIIMS medical entrance exam previous year question papers with detailed solutions.',
    category: 'Entrance Exams',
    link: 'https://www.aiimsexams.ac.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '📄',
    tags: ['AIIMS', 'Medical', 'Previous Papers'],
    state: 'All India'
  },

  // NEET Preparation - YouTube
  {
    id: 19,
    title: 'Physics Wallah - NEET',
    description: 'Complete NEET preparation for Biology, Physics, and Chemistry. Free lectures by expert teachers.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@PhysicsWallah',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['NEET', 'Biology', 'Free', 'Complete Course'],
    state: 'All India'
  },
  {
    id: 20,
    title: 'Dr. Vani Sood - NEET Biology',
    description: 'Comprehensive NEET Biology preparation with NCERT focus. Best for conceptual clarity.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@DrVaniSood',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['NEET', 'Biology', 'NCERT'],
    state: 'All India'
  },

  // NEET Telegram
  {
    id: 21,
    title: 'NEET Study Materials 2025',
    description: 'Daily NEET questions, biology flashcards, chemistry notes, and physics formulas. 100K+ members.',
    category: 'Online Learning',
    link: 'https://t.me/neetpreparation',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Telegram',
    icon: '💬',
    tags: ['NEET', 'Study Material', 'Daily Questions'],
    state: 'All India'
  },

  // ==================== CLASS 12 - COMMERCE ====================
  // CA & Professional Courses
  {
    id: 22,
    title: 'ICAI Student Portal - CA Foundation',
    description: 'Official Institute of Chartered Accountants of India portal for CA Foundation registration, study material, and exam info.',
    category: 'Entrance Exams',
    link: 'https://www.icai.org/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '💼',
    tags: ['CA', 'Chartered Accountant', 'ICAI', 'Foundation'],
    state: 'All India'
  },
  {
    id: 23,
    title: 'ICSI - CS Foundation',
    description: 'Company Secretary course by ICSI. Registration, syllabus, and study materials for CS Foundation.',
    category: 'Entrance Exams',
    link: 'https://www.icsi.edu/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '📊',
    tags: ['CS', 'Company Secretary', 'ICSI'],
    state: 'All India'
  },
  {
    id: 24,
    title: 'CMA Foundation - ICMAI',
    description: 'Cost and Management Accountant course information, syllabus, and admission process.',
    category: 'Entrance Exams',
    link: 'https://www.icmai.in/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '💰',
    tags: ['CMA', 'Management Accountant', 'ICMAI'],
    state: 'All India'
  },

  // Management Entrance
  {
    id: 25,
    title: 'CUET (UG) - Commerce Entrance',
    description: 'Common University Entrance Test for admission to B.Com, BBA, and other commerce programs in central universities.',
    category: 'Entrance Exams',
    link: 'https://cuet.samarth.ac.in/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎓',
    tags: ['CUET', 'B.Com', 'BBA', 'Central Universities'],
    state: 'All India'
  },
  {
    id: 26,
    title: 'IPM Aptitude Test (IIM Indore & Rohtak)',
    description: 'Integrated Programme in Management - 5-year MBA program entrance exam by IIMs.',
    category: 'Entrance Exams',
    link: 'https://www.iimidr.ac.in/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏫',
    tags: ['IPM', 'IIM', 'Management', 'Integrated MBA'],
    state: 'All India'
  },

  // CA Preparation - YouTube
  {
    id: 27,
    title: 'CA Wallah - CA Foundation',
    description: 'Complete CA Foundation preparation by Alakh Pandey. Free lectures for all subjects.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@CAWallahbyPW',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['CA Foundation', 'Free', 'Complete Course'],
    state: 'All India'
  },
  {
    id: 28,
    title: 'Commerce Wallah - Class 12 + Entrance',
    description: 'Board exam preparation + CUET/entrance exams for commerce students. Accounts, Economics, Business Studies.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@CommerceWallahbyPW',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['Board Exam', 'CUET', 'Commerce'],
    state: 'All India'
  },

  // Commerce Telegram
  {
    id: 29,
    title: 'CA Foundation Study Group',
    description: 'CA Foundation students community. Daily MCQs, notes, amendments, and doubt solving. 30K+ members.',
    category: 'Online Learning',
    link: 'https://t.me/cafoundation2025',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Telegram',
    icon: '💬',
    tags: ['CA Foundation', 'Community', 'Study Group'],
    state: 'All India'
  },

  // ==================== CLASS 12 - ARTS/HUMANITIES ====================
  // Law Entrance
  {
    id: 30,
    title: 'CLAT Consortium - Official Portal',
    description: 'Common Law Admission Test for National Law Universities. Registration, syllabus, and sample papers.',
    category: 'Entrance Exams',
    link: 'https://consortiumofnlus.ac.in/',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '⚖️',
    tags: ['CLAT', 'Law', 'NLU', 'Entrance'],
    state: 'All India'
  },
  {
    id: 31,
    title: 'AILET - NLU Delhi',
    description: 'All India Law Entrance Test for admission to National Law University, Delhi.',
    category: 'Entrance Exams',
    link: 'https://nludelhi.ac.in/',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '⚖️',
    tags: ['AILET', 'Law', 'NLU Delhi'],
    state: 'All India'
  },

  // Design Entrance
  {
    id: 32,
    title: 'NID Admission - Design Entrance',
    description: 'National Institute of Design entrance exam for Bachelor of Design programs. Portfolio preparation guidelines.',
    category: 'Entrance Exams',
    link: 'https://www.nid.edu/',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎨',
    tags: ['NID', 'Design', 'BDes', 'Portfolio'],
    state: 'All India'
  },
  {
    id: 33,
    title: 'NIFT Entrance Exam',
    description: 'National Institute of Fashion Technology entrance for fashion design and technology programs.',
    category: 'Entrance Exams',
    link: 'https://www.nift.ac.in/',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '👗',
    tags: ['NIFT', 'Fashion Design', 'Entrance'],
    state: 'All India'
  },
  {
    id: 34,
    title: 'UCEED - IIT Design Entrance',
    description: 'Undergraduate Common Entrance Exam for Design (B.Des) at IIT Bombay, Guwahati, and Hyderabad.',
    category: 'Entrance Exams',
    link: 'https://uceed.iitb.ac.in/',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎨',
    tags: ['UCEED', 'IIT', 'Design', 'BDes'],
    state: 'All India'
  },

  // Mass Communication
  {
    id: 35,
    title: 'IIMC Entrance Exam',
    description: 'Indian Institute of Mass Communication entrance for journalism and mass communication programs.',
    category: 'Entrance Exams',
    link: 'https://iimc.gov.in/',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '📰',
    tags: ['IIMC', 'Journalism', 'Mass Communication'],
    state: 'All India'
  },

  // CLAT Preparation - YouTube
  {
    id: 36,
    title: 'Legal Pathshala - CLAT Preparation',
    description: 'Complete CLAT preparation with current affairs, legal reasoning, and logical reasoning.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@LegalPathshalaGroup',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['CLAT', 'Law', 'Free'],
    state: 'All India'
  },
  {
    id: 37,
    title: 'The Design Sketchbook',
    description: 'NID, NIFT, UCEED preparation with portfolio building, sketching tutorials, and design fundamentals.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@TheDesignSketchbook',
    targetClass: '12th',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['Design', 'NID', 'NIFT', 'Portfolio'],
    state: 'All India'
  },

  // ==================== SCHOLARSHIPS (ALL) ====================
  {
    id: 38,
    title: 'National Scholarship Portal (NSP)',
    description: 'One-stop platform for all Central and State Government scholarships. Apply for pre-matric, post-matric, and merit scholarships.',
    category: 'Scholarship Portals',
    link: 'https://scholarships.gov.in/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '💰',
    tags: ['Scholarship', 'Government', 'All India'],
    state: 'All India'
  },
  {
    id: 39,
    title: 'Jagananna Vidya Deevena',
    description: 'AP Government full fee reimbursement scheme for SC/ST/BC/Minority/EBC/Kapu students pursuing higher education.',
    category: 'Govt. Schemes',
    link: 'https://jnanabhumi.ap.gov.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎓',
    tags: ['Fee Reimbursement', 'Andhra Pradesh', 'Scholarship'],
    state: 'Andhra Pradesh'
  },
  {
    id: 40,
    title: 'TS Fee Reimbursement',
    description: 'Telangana State fee reimbursement for SC/ST/BC/Minority students in professional courses.',
    category: 'Govt. Schemes',
    link: 'https://telanganaepass.cgg.gov.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎓',
    tags: ['Fee Reimbursement', 'Telangana', 'Scholarship'],
    state: 'Telangana'
  },
  {
    id: 41,
    title: 'INSPIRE Scholarship (DST)',
    description: 'Central Government scholarship for top 1% students in Class 12 board exams pursuing science courses.',
    category: 'Scholarship Portals',
    link: 'https://online-inspire.gov.in/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '🔬',
    tags: ['Merit Scholarship', 'Science', 'DST'],
    state: 'All India'
  },
  {
    id: 42,
    title: 'PM Scholarship Scheme',
    description: 'Scholarship for wards of ex-servicemen, ex-Coast Guard personnel, and police officials killed in action.',
    category: 'Scholarship Portals',
    link: 'https://ksb.gov.in/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🪖',
    tags: ['PM Scholarship', 'Defence', 'Government'],
    state: 'All India'
  },

  // ==================== SKILL DEVELOPMENT (ALL) ====================
  {
    id: 43,
    title: 'SWAYAM - Free Online Courses',
    description: 'Government initiative offering 2000+ free MOOCs from Class 9 to post-graduation. Earn certificates from IITs, IIMs.',
    category: 'Skill Development',
    link: 'https://swayam.gov.in/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '🌐',
    tags: ['Free Courses', 'Government', 'Certification'],
    state: 'All India'
  },
  {
    id: 44,
    title: 'NPTEL - IIT/IISc Courses',
    description: 'Free online certification courses in engineering, sciences, and humanities from IITs and IISc.',
    category: 'Skill Development',
    link: 'https://nptel.ac.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '🎓',
    tags: ['Engineering', 'IIT', 'Free', 'Certification'],
    state: 'All India'
  },
  {
    id: 45,
    title: 'Coursera for Campus',
    description: 'Access to 7,000+ courses and certifications. Financial aid available for students who cannot afford.',
    category: 'Skill Development',
    link: 'https://www.coursera.org/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: true,
    resourceType: 'Platform',
    icon: '💻',
    tags: ['Online Courses', 'Certification', 'Financial Aid'],
    state: 'All India'
  },
  {
    id: 46,
    title: 'Google Digital Unlocked',
    description: 'Free digital marketing certification course by Google. Recognized by industry, helps with career building.',
    category: 'Skill Development',
    link: 'https://learndigital.withgoogle.com/digitalunlocked',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '📱',
    tags: ['Digital Marketing', 'Google', 'Free', 'Certification'],
    state: 'All India'
  },
  {
    id: 47,
    title: 'Microsoft Learn',
    description: 'Free tech courses and certifications from Microsoft. Learn cloud computing, AI, programming, and more.',
    category: 'Skill Development',
    link: 'https://learn.microsoft.com/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '🪟',
    tags: ['Microsoft', 'Tech Skills', 'Free', 'Cloud'],
    state: 'All India'
  },
  {
    id: 48,
    title: 'LinkedIn Learning (Free Trial)',
    description: '1-month free trial for thousands of professional courses. Business, tech, creative skills covered.',
    category: 'Skill Development',
    link: 'https://www.linkedin.com/learning/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: true,
    resourceType: 'Platform',
    icon: '💼',
    tags: ['Professional Skills', 'LinkedIn', 'Free Trial'],
    state: 'All India'
  },
  {
    id: 49,
    title: 'AP State Skill Development (APSSDC)',
    description: 'Skill development programs and workshops for youth in Andhra Pradesh. Industry-oriented training.',
    category: 'Skill Development',
    link: 'https://apssdc.in/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🛠️',
    tags: ['Skill Development', 'Andhra Pradesh', 'Vocational'],
    state: 'Andhra Pradesh'
  },

  // ==================== E-BOOKS & STUDY MATERIALS ====================
  {
    id: 50,
    title: 'National Digital Library of India',
    description: 'Vast repository of e-books, articles, videos from IIT Kharagpur. 5 crore+ learning resources.',
    category: 'E-Books',
    link: 'https://ndl.iitkgp.ac.in/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '📚',
    tags: ['E-Books', 'Digital Library', 'IIT', 'Free'],
    state: 'All India'
  },
  {
    id: 51,
    title: 'ePathshala by NCERT',
    description: 'Digital access to all NCERT textbooks, audio-video resources, and interactive periodicals.',
    category: 'E-Books',
    link: 'https://epathshala.nic.in/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '📖',
    tags: ['NCERT', 'Textbooks', 'Free', 'Government'],
    state: 'All India'
  },
  {
    id: 52,
    title: 'e-ShodhSindhu',
    description: 'Access to e-journals, books, and databases for higher education students. Research papers and articles.',
    category: 'E-Books',
    link: 'https://ess.inflibnet.ac.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '📄',
    tags: ['Research', 'Journals', 'Academic', 'Free'],
    state: 'All India'
  },

  // ==================== COMPETITIVE EXAMS ====================
  {
    id: 53,
    title: 'UPSC Official Website',
    description: 'Union Public Service Commission portal for Civil Services, NDA, CDS, and other competitive exams.',
    category: 'Competitive Exams',
    link: 'https://www.upsc.gov.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏛️',
    tags: ['UPSC', 'Civil Services', 'Government Jobs'],
    state: 'All India'
  },
  {
    id: 54,
    title: 'NDA Entrance (UPSC)',
    description: 'National Defence Academy entrance exam for Army, Navy, Air Force. After Class 12 (any stream).',
    category: 'Competitive Exams',
    link: 'https://www.upsc.gov.in/examinations/nda',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🪖',
    tags: ['NDA', 'Defence', 'Armed Forces'],
    state: 'All India'
  },
  {
    id: 55,
    title: 'SSC Official Portal',
    description: 'Staff Selection Commission exams for central government jobs. CGL, CHSL, MTS, and more.',
    category: 'Competitive Exams',
    link: 'https://ssc.nic.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏢',
    tags: ['SSC', 'Government Jobs', 'Competitive'],
    state: 'All India'
  },
  {
    id: 56,
    title: 'IBPS - Bank Exams',
    description: 'Institute of Banking Personnel Selection. PO, Clerk, SO exams for public sector banks.',
    category: 'Competitive Exams',
    link: 'https://www.ibps.in/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏦',
    tags: ['Banking', 'IBPS', 'Government Jobs'],
    state: 'All India'
  },

  // State-specific competitive exams
  {
    id: 57,
    title: 'APPSC - AP Public Service',
    description: 'Andhra Pradesh Public Service Commission for state government jobs and civil services.',
    category: 'Competitive Exams',
    link: 'https://psc.ap.gov.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏛️',
    tags: ['APPSC', 'Andhra Pradesh', 'State Jobs'],
    state: 'Andhra Pradesh'
  },
  {
    id: 58,
    title: 'TSPSC - Telangana Public Service',
    description: 'Telangana State Public Service Commission for state government recruitment exams.',
    category: 'Competitive Exams',
    link: 'https://www.tspsc.gov.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏛️',
    tags: ['TSPSC', 'Telangana', 'State Jobs'],
    state: 'Telangana'
  },
  {
    id: 59,
    title: 'MPSC - Maharashtra Public Service',
    description: 'Maharashtra Public Service Commission for state civil services and other government positions.',
    category: 'Competitive Exams',
    link: 'https://mpsc.gov.in/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Website',
    icon: '🏛️',
    tags: ['MPSC', 'Maharashtra', 'State Jobs'],
    state: 'Maharashtra'
  },

  // ==================== ADDITIONAL YOUTUBE CHANNELS ====================
  {
    id: 60,
    title: 'Study IQ Education',
    description: 'Free competitive exam preparation for UPSC, SSC, Banking. Current affairs and general knowledge.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@StudyIQ',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['UPSC', 'SSC', 'Competitive', 'Free'],
    state: 'All India'
  },
  {
    id: 61,
    title: 'Eduniti - Mathematics',
    description: 'Advanced mathematics for JEE, Olympiads, and board exams. Problem-solving techniques.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@EdunitiMathematics',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['Mathematics', 'JEE', 'Olympiad'],
    state: 'All India'
  },
  {
    id: 62,
    title: 'Sunil Adhikari - Accounts',
    description: 'Class 11-12 Accountancy, CA Foundation accounts preparation. Crystal clear explanations.',
    category: 'Online Learning',
    link: 'https://www.youtube.com/@SunilAdhikariAccounts',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'YouTube',
    icon: '📺',
    tags: ['Accountancy', 'Commerce', 'Board Exam'],
    state: 'All India'
  },

  // ==================== TELEGRAM COMMUNITIES ====================
  {
    id: 63,
    title: 'UPSC Aspirants Hub',
    description: 'Daily current affairs, monthly magazines, prelims test series, and optional subject notes.',
    category: 'Online Learning',
    link: 'https://t.me/upscaspirants',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Telegram',
    icon: '💬',
    tags: ['UPSC', 'Current Affairs', 'Community'],
    state: 'All India'
  },
  {
    id: 64,
    title: 'Free Study Materials for Students',
    description: 'NCERT, CBSE, competitive exam PDFs, previous papers, and notes. All classes and subjects.',
    category: 'E-Books',
    link: 'https://t.me/freestudymaterials',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Telegram',
    icon: '💬',
    tags: ['Study Material', 'PDFs', 'Notes'],
    state: 'All India'
  },

  // ==================== CAREER GUIDANCE PLATFORMS ====================
  {
    id: 65,
    title: 'iDreamCareer - Free Counseling',
    description: 'Free career counseling sessions, webinars, and guidance for Class 10-12 students.',
    category: 'Career Guidance',
    link: 'https://www.idreamcareer.com/',
    targetClass: 'All',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '🎯',
    tags: ['Career Counseling', 'Free', 'Webinars'],
    state: 'All India'
  },
  {
    id: 66,
    title: 'Univariety - Admission Guidance',
    description: 'College admission guidance, entrance exam prep, and career mentoring platform.',
    category: 'Career Guidance',
    link: 'https://www.univariety.com/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: true,
    resourceType: 'Platform',
    icon: '🎓',
    tags: ['Admission', 'Mentoring', 'Premium'],
    state: 'All India'
  },
  {
    id: 67,
    title: 'Leverage Edu - Study Abroad',
    description: 'Free counseling for study abroad opportunities. Helps with application, visa, and scholarships.',
    category: 'Career Guidance',
    link: 'https://leverageedu.com/',
    targetClass: '12th',
    targetStream: 'All',
    isPaid: false,
    resourceType: 'Platform',
    icon: '✈️',
    tags: ['Study Abroad', 'Counseling', 'Free'],
    state: 'All India'
  },

  // ==================== ADDITIONAL SPECIALIZED RESOURCES ====================
  {
    id: 68,
    title: 'GeeksforGeeks - Programming',
    description: 'Comprehensive platform for learning programming, data structures, algorithms, and competitive coding.',
    category: 'Skill Development',
    link: 'https://www.geeksforgeeks.org/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '💻',
    tags: ['Programming', 'Coding', 'Free', 'Algorithms'],
    state: 'All India'
  },
  {
    id: 69,
    title: 'HackerRank - Coding Practice',
    description: 'Practice coding, prepare for technical interviews, and participate in programming competitions.',
    category: 'Skill Development',
    link: 'https://www.hackerrank.com/',
    targetClass: '12th',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Platform',
    icon: '👨‍💻',
    tags: ['Coding', 'Interview Prep', 'Free'],
    state: 'All India'
  },
  {
    id: 70,
    title: 'Investopedia - Financial Literacy',
    description: 'Learn about stocks, mutual funds, financial planning, and investment basics for commerce students.',
    category: 'Skill Development',
    link: 'https://www.investopedia.com/',
    targetClass: '12th',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '📈',
    tags: ['Finance', 'Investment', 'Stock Market'],
    state: 'All India'
  },
  // ==================== CAREER SPECIFIC RESOURCES (NEW) ====================
  // Tech & AI
  {
    id: 101,
    title: 'DeepLearning.AI - Andrew Ng',
    description: 'World-class AI education. Specializations in Deep Learning, NLP, and TensorFlow. The gold standard for AI Engineers.',
    category: 'Online Learning',
    link: 'https://www.deeplearning.ai/',
    targetClass: 'All',
    targetStream: 'Science',
    isPaid: true,
    resourceType: 'Website',
    icon: '🤖',
    tags: ['AI/ML Engineer', 'Deep Learning', 'Python', 'Data Science'],
    state: 'All India'
  },
  {
    id: 102,
    title: 'freeCodeCamp - Full Stack',
    description: 'Learn to code for free. HTML, CSS, JavaScript, Python, and more. Build projects to earn certifications.',
    category: 'Skill Development',
    link: 'https://www.freecodecamp.org/',
    targetClass: 'All',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Platform',
    icon: '💻',
    tags: ['Software Developer', 'Web Development', 'Coding', 'Free'],
    state: 'All India'
  },
  {
    id: 103,
    title: 'CS50: Introduction to Computer Science',
    description: 'Harvard University\'s introduction to the intellectual enterprises of computer science and the art of programming.',
    category: 'Online Learning',
    link: 'https://pll.harvard.edu/course/cs50-introduction-computer-science',
    targetClass: 'All',
    targetStream: 'Science',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎓',
    tags: ['Computer Science', 'Coding', 'Harvard', 'Free'],
    state: 'All India'
  },

  // Finance & Management
  {
    id: 104,
    title: 'Investopedia Academy',
    description: 'Comprehensive financial education. Learn about stocks, trading, and investment banking concepts.',
    category: 'Online Learning',
    link: 'https://www.investopedia.com/',
    targetClass: 'All',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '📈',
    tags: ['Investment Banker', 'Finance', 'Economics', 'Trading'],
    state: 'All India'
  },
  {
    id: 105,
    title: 'CFI - Corporate Finance Institute',
    description: 'Practical financial modeling and valuation courses. Essential for aspiring Investment Bankers and Financial Analysts.',
    category: 'Skill Development',
    link: 'https://corporatefinanceinstitute.com/',
    targetClass: 'All',
    targetStream: 'Commerce',
    isPaid: true,
    resourceType: 'Platform',
    icon: '📊',
    tags: ['Investment Banker', 'Financial Modeling', 'Certification'],
    state: 'All India'
  },
  {
    id: 106,
    title: 'Product School',
    description: 'Resources, events, and certifications for aspiring Product Managers. Learn from PMs at top tech companies.',
    category: 'Career Guidance',
    link: 'https://productschool.com/',
    targetClass: 'All',
    targetStream: 'Commerce',
    isPaid: false,
    resourceType: 'Website',
    icon: '📦',
    tags: ['Product Manager', 'Management', 'Tech'],
    state: 'All India'
  },

  // Design & Arts
  {
    id: 107,
    title: 'Behance - Creative Portfolios',
    description: 'Showcase and discover creative work. Essential for Designers to build portfolios and find inspiration.',
    category: 'Skill Development',
    link: 'https://www.behance.net/',
    targetClass: 'All',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '🎨',
    tags: ['UX/UI Designer', 'Graphic Design', 'Portfolio', 'Inspiration'],
    state: 'All India'
  },
  {
    id: 108,
    title: 'Nielsen Norman Group (NN/g)',
    description: 'World leaders in Research-Based User Experience. Articles and reports for aspiring UX Designers.',
    category: 'Online Learning',
    link: 'https://www.nngroup.com/',
    targetClass: 'All',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '📱',
    tags: ['UX/UI Designer', 'User Research', 'Usability'],
    state: 'All India'
  },
  {
    id: 109,
    title: 'Bar Council of India',
    description: 'Statutory body regulating the legal practice and legal education in India. Rules, news, and resources for law students.',
    category: 'Career Guidance',
    link: 'http://www.barcouncilofindia.org/',
    targetClass: 'All',
    targetStream: 'Arts',
    isPaid: false,
    resourceType: 'Website',
    icon: '⚖️',
    tags: ['Corporate Lawyer', 'Law', 'Legal Education'],
    state: 'All India'
  },
];
