import type { QuestionBank } from './riasec-scoring';

export const questionBankFor12th: QuestionBank = {
    // BASELINE QUESTIONS
    baseline: [
        {
            id: '12-b1',
            type: 'scenario',
            category: 'baseline',
            text: 'After 12th, what is your immediate priority?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'degree',
                    icon: '🎓',
                    title: 'Top Degree',
                    description: 'Get into a prestigious college for a 3-4 year degree',
                    riasecWeights: { I: 5, E: 5 },
                },
                {
                    id: 'skill',
                    icon: '🛠️',
                    title: 'Practical Skills',
                    description: 'Learn specific skills to start working or building sooner',
                    riasecWeights: { R: 8, A: 5 },
                },
                {
                    id: 'explore',
                    icon: '🌍',
                    title: 'Explore Options',
                    description: 'Take a gap year or try different short courses',
                    riasecWeights: { A: 5, S: 5 },
                },
                {
                    id: 'job',
                    icon: '💼',
                    title: 'Start Earning',
                    description: 'Find a job or start a business immediately',
                    riasecWeights: { E: 8, C: 5 },
                },
            ],
        },
        {
            id: '12-b2',
            type: 'scenario',
            category: 'baseline',
            text: 'Which work environment appeals to you most?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'corp',
                    icon: '🏢',
                    title: 'Corporate Office',
                    description: 'Professional setting, meetings, and structured growth',
                    riasecWeights: { E: 10, C: 10 },
                },
                {
                    id: 'lab',
                    icon: '🔬',
                    title: 'Lab / Tech Center',
                    description: 'Quiet, focused environment with advanced equipment',
                    riasecWeights: { I: 12, R: 8 },
                },
                {
                    id: 'field',
                    icon: '🌲',
                    title: 'Outdoors / Field',
                    description: 'Working at different sites, traveling, or in nature',
                    riasecWeights: { R: 12, S: 5 },
                },
                {
                    id: 'studio',
                    icon: '🎨',
                    title: 'Creative Studio',
                    description: 'Relaxed, colorful space for brainstorming and creating',
                    riasecWeights: { A: 12 },
                },
            ],
        },
        {
            id: '12-b3',
            type: 'ranking',
            category: 'baseline',
            text: 'Rank these factors for your dream career (Top = Most Important):',
            riasecWeights: {},
            options: [
                'High Salary & Wealth',
                'Job Security & Stability',
                'Work-Life Balance',
                'Impact on Society',
                'Intellectual Challenge',
                'Creative Freedom',
            ],
        },
        {
            id: '12-b4',
            type: 'slider-grid',
            category: 'baseline',
            text: 'Rate your ACTUAL ability in these areas (Be honest!):',
            riasecWeights: {},
            skills: [
                { name: 'Logical Reasoning / Math', riasec: 'I' },
                { name: 'Communication / Speaking', riasec: 'E' },
                { name: 'Creative / Artistic Design', riasec: 'A' },
                { name: 'Empathy / Listening', riasec: 'S' },
                { name: 'Physical / Hands-on Work', riasec: 'R' },
                { name: 'Organization / Detail', riasec: 'C' },
            ],
        },
    ],

    // DEEP-DIVE QUESTIONS
    deepdive: {
        realistic: [
            {
                id: '12-r1',
                type: 'slider',
                category: 'deepdive',
                text: 'How interested are you in engineering or technical fields?',
                minLabel: 'Not at all',
                maxLabel: 'My Dream',
                primaryRIASEC: 'R',
                riasecWeights: { R: 15 },
            },
            {
                id: '12-r2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which engineering branch sounds most exciting?',
                riasecWeights: {},
                options: [
                    { text: 'Computer Science (Coding)', riasecWeights: { R: 8, I: 10, C: 5 } },
                    { text: 'Mechanical / Civil (Building)', riasecWeights: { R: 15 } },
                    { text: 'Electronics / Robotics', riasecWeights: { R: 12, I: 8 } },
                    { text: 'Not interested in engineering', riasecWeights: { R: 0 } },
                ],
            },
            {
                id: '12-r3',
                type: 'scenario',
                category: 'deepdive',
                text: 'You have to learn a new software. How do you do it?',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'try',
                        icon: '🖱️',
                        title: 'Just Click Around',
                        description: 'Explore the menus and try to figure it out by doing',
                        riasecWeights: { R: 12 },
                    },
                    {
                        id: 'read',
                        icon: '📖',
                        title: 'Read Manual',
                        description: 'Read the documentation or watch a full tutorial first',
                        riasecWeights: { I: 8, C: 5 },
                    },
                ],
            },
            {
                id: '12-r4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'Which of these careers appeal to you?',
                riasecWeights: {},
                options: [
                    { text: 'Pilot or Aviation', riasecWeights: { R: 15, E: 5 } },
                    { text: 'Architect', riasecWeights: { R: 10, A: 10, I: 5 } },
                    { text: 'Surgeon', riasecWeights: { R: 10, I: 10, S: 5 } },
                    { text: 'Software Developer', riasecWeights: { R: 5, I: 10, C: 5 } },
                ],
            },
            {
                id: '12-r5',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you enjoy working outdoors or with nature?',
                minLabel: 'Prefer Indoors',
                maxLabel: 'Love Outdoors',
                primaryRIASEC: 'R',
                riasecWeights: { R: 15 },
            },
            {
                id: '12-r6',
                type: 'scenario',
                category: 'deepdive',
                text: 'Your car/bike breaks down on the road. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'check',
                        icon: '🔧',
                        title: 'Check Engine',
                        description: 'Open the hood and try to see what\'s wrong',
                        riasecWeights: { R: 15 },
                    },
                    {
                        id: 'call',
                        icon: '📱',
                        title: 'Call Mechanic',
                        description: 'Call for roadside assistance immediately',
                        riasecWeights: { C: 5 },
                    },
                ],
            },
        ],

        investigative: [
            {
                id: '12-i1',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you enjoy deep research and academic study?',
                minLabel: 'Boring',
                maxLabel: 'Love it',
                primaryRIASEC: 'I',
                riasecWeights: { I: 15 },
            },
            {
                id: '12-i2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which field of science interests you most?',
                riasecWeights: {},
                options: [
                    { text: 'Medicine & Biology', riasecWeights: { I: 12, S: 5 } },
                    { text: 'Physics & Astronomy', riasecWeights: { I: 15 } },
                    { text: 'Data Science & AI', riasecWeights: { I: 12, C: 5 } },
                    { text: 'Psychology & Human Behavior', riasecWeights: { I: 10, S: 8 } },
                ],
            },
            {
                id: '12-i3',
                type: 'scenario',
                category: 'deepdive',
                text: 'You encounter a difficult problem in your studies. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'deep',
                        icon: '🕵️',
                        title: 'Dig Deeper',
                        description: 'Spend hours researching until you fully understand it',
                        riasecWeights: { I: 15 },
                    },
                    {
                        id: 'ask',
                        icon: '🙋',
                        title: 'Ask for Help',
                        description: 'Ask a teacher or friend to explain it simply',
                        riasecWeights: { S: 5 },
                    },
                ],
            },
            {
                id: '12-i4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'Ideally, your job would involve...',
                riasecWeights: {},
                options: [
                    { text: 'Solving complex mathematical problems', riasecWeights: { I: 15 } },
                    { text: 'Conducting experiments in a lab', riasecWeights: { I: 15, R: 5 } },
                    { text: 'Analyzing trends and predicting the future', riasecWeights: { I: 12, C: 5 } },
                    { text: 'Diagnosing diseases', riasecWeights: { I: 10, S: 5 } },
                ],
            },
            {
                id: '12-i5',
                type: 'slider',
                category: 'deepdive',
                text: 'How comfortable are you with abstract concepts and theories?',
                minLabel: 'Prefer Concrete',
                maxLabel: 'Love Abstract',
                primaryRIASEC: 'I',
                riasecWeights: { I: 15 },
            },
            {
                id: '12-i6',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which type of reading material do you prefer?',
                riasecWeights: {},
                options: [
                    { text: 'Scientific Journals / Non-fiction', riasecWeights: { I: 15 } },
                    { text: 'Biographies of famous people', riasecWeights: { I: 5, E: 5, S: 5 } },
                    { text: 'Novels / Fiction', riasecWeights: { A: 10 } },
                    { text: 'News / Current Affairs', riasecWeights: { I: 5, S: 5, E: 5 } },
                ],
            },
        ],

        artistic: [
            {
                id: '12-a1',
                type: 'slider',
                category: 'deepdive',
                text: 'Could you see yourself in a career where "creativity" is the main requirement?',
                minLabel: 'No way',
                maxLabel: 'Absolutely',
                primaryRIASEC: 'A',
                riasecWeights: { A: 15 },
            },
            {
                id: '12-a2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which creative field appeals to you?',
                riasecWeights: {},
                options: [
                    { text: 'Design (Graphic, Fashion, Interior)', riasecWeights: { A: 15 } },
                    { text: 'Media (Journalism, Film, YouTube)', riasecWeights: { A: 12, E: 5 } },
                    { text: 'Writing & Content Creation', riasecWeights: { A: 12, I: 3 } },
                    { text: 'Performing Arts (Music, Dance, Acting)', riasecWeights: { A: 15 } },
                ],
            },
            {
                id: '12-a3',
                type: 'scenario',
                category: 'deepdive',
                text: 'You are given a task with no strict rules. You feel...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'excited',
                        icon: '🤩',
                        title: 'Excited',
                        description: 'I love the freedom to do it my way',
                        riasecWeights: { A: 15 },
                    },
                    {
                        id: 'anxious',
                        icon: '😰',
                        title: 'Anxious',
                        description: 'I prefer clear instructions on what to do',
                        riasecWeights: { C: 10, A: -5 },
                    },
                ],
            },
            {
                id: '12-a4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You would enjoy a job that lets you...',
                riasecWeights: {},
                options: [
                    { text: 'Express your own ideas', riasecWeights: { A: 10 } },
                    { text: 'Make things look beautiful', riasecWeights: { A: 10 } },
                    { text: 'Perform in front of an audience', riasecWeights: { A: 10, E: 5 } },
                    { text: 'Write stories or articles', riasecWeights: { A: 10 } },
                ],
            },
            {
                id: '12-a5',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you value aesthetics and beauty in your environment?',
                minLabel: 'Not much',
                maxLabel: 'A lot',
                primaryRIASEC: 'A',
                riasecWeights: { A: 10 },
            },
            {
                id: '12-a6',
                type: 'scenario',
                category: 'deepdive',
                text: 'You need to present your project. You focus on...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'style',
                        icon: '🎨',
                        title: 'Style & Impact',
                        description: 'Making it look amazing and memorable',
                        riasecWeights: { A: 15 },
                    },
                    {
                        id: 'facts',
                        icon: '📊',
                        title: 'Facts & Data',
                        description: 'Ensuring all the information is correct',
                        riasecWeights: { I: 5, C: 10 },
                    },
                ],
            },
        ],

        social: [
            {
                id: '12-s1',
                type: 'slider',
                category: 'deepdive',
                text: 'How important is "helping others" in your career choice?',
                minLabel: 'Not important',
                maxLabel: 'Very important',
                primaryRIASEC: 'S',
                riasecWeights: { S: 15 },
            },
            {
                id: '12-s2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which "helping" career interests you?',
                riasecWeights: {},
                options: [
                    { text: 'Doctor / Nurse / Healthcare', riasecWeights: { S: 10, I: 10, R: 5 } },
                    { text: 'Teacher / Professor', riasecWeights: { S: 15, A: 5 } },
                    { text: 'Psychologist / Counselor', riasecWeights: { S: 15, I: 8 } },
                    { text: 'Social Worker / NGO', riasecWeights: { S: 15, E: 5 } },
                ],
            },
            {
                id: '12-s3',
                type: 'scenario',
                category: 'deepdive',
                text: 'In a group project, a member is not contributing. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'talk',
                        icon: '💬',
                        title: 'Talk Privately',
                        description: 'Ask them if everything is okay and how you can help',
                        riasecWeights: { S: 15 },
                    },
                    {
                        id: 'report',
                        icon: '📢',
                        title: 'Report Them',
                        description: 'Tell the teacher or leader so the project doesn\'t suffer',
                        riasecWeights: { E: 5, C: 5 },
                    },
                ],
            },
            {
                id: '12-s4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You are good at...',
                riasecWeights: {},
                options: [
                    { text: 'Explaining things clearly', riasecWeights: { S: 10 } },
                    { text: 'Listening without judging', riasecWeights: { S: 10 } },
                    { text: 'Motivating people', riasecWeights: { S: 8, E: 8 } },
                    { text: 'Caring for sick people or animals', riasecWeights: { S: 10, R: 3 } },
                ],
            },
            {
                id: '12-s5',
                type: 'slider',
                category: 'deepdive',
                text: 'How easily do you make new friends?',
                minLabel: 'Not easily',
                maxLabel: 'Very easily',
                primaryRIASEC: 'S',
                riasecWeights: { S: 10, E: 5 },
            },
            {
                id: '12-s6',
                type: 'scenario',
                category: 'deepdive',
                text: 'A friend is upset about a bad grade. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'comfort',
                        icon: '🤗',
                        title: 'Comfort Them',
                        description: 'Listen to them and offer emotional support',
                        riasecWeights: { S: 15 },
                    },
                    {
                        id: 'advice',
                        icon: '💡',
                        title: 'Give Advice',
                        description: 'Tell them how to study better next time',
                        riasecWeights: { I: 5, E: 5 },
                    },
                ],
            },
        ],

        enterprising: [
            {
                id: '12-e1',
                type: 'slider',
                category: 'deepdive',
                text: 'How ambitious are you about leadership and business success?',
                minLabel: 'Not ambitious',
                maxLabel: 'Very ambitious',
                primaryRIASEC: 'E',
                riasecWeights: { E: 15 },
            },
            {
                id: '12-e2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which business role appeals to you?',
                riasecWeights: {},
                options: [
                    { text: 'CEO / Entrepreneur (Own Business)', riasecWeights: { E: 15, R: 5 } },
                    { text: 'Marketing & Sales Manager', riasecWeights: { E: 15, A: 5 } },
                    { text: 'Investment Banker / Finance', riasecWeights: { E: 10, C: 10 } },
                    { text: 'Corporate Lawyer', riasecWeights: { E: 12, I: 5 } },
                ],
            },
            {
                id: '12-e3',
                type: 'scenario',
                category: 'deepdive',
                text: 'You have a great idea for a product. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'pitch',
                        icon: '🎤',
                        title: 'Pitch It',
                        description: 'Start telling everyone and try to get funding/support',
                        riasecWeights: { E: 15 },
                    },
                    {
                        id: 'plan',
                        icon: '📝',
                        title: 'Plan It',
                        description: 'Write a detailed business plan and analyze risks first',
                        riasecWeights: { C: 10, I: 5 },
                    },
                ],
            },
            {
                id: '12-e4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You enjoy...',
                riasecWeights: {},
                options: [
                    { text: 'Persuading people to your point of view', riasecWeights: { E: 10 } },
                    { text: 'Taking risks for big rewards', riasecWeights: { E: 10 } },
                    { text: 'Leading a team to victory', riasecWeights: { E: 10 } },
                    { text: 'Negotiating deals', riasecWeights: { E: 10 } },
                ],
            },
            {
                id: '12-e5',
                type: 'slider',
                category: 'deepdive',
                text: 'How competitive are you?',
                minLabel: 'Not at all',
                maxLabel: 'Very competitive',
                primaryRIASEC: 'E',
                riasecWeights: { E: 15 },
            },
            {
                id: '12-e6',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'What drives you most?',
                riasecWeights: {},
                options: [
                    { text: 'Recognition and Status', riasecWeights: { E: 15 } },
                    { text: 'Money and Wealth', riasecWeights: { E: 12, C: 5 } },
                    { text: 'Helping others', riasecWeights: { S: 15 } },
                    { text: 'Knowledge and Truth', riasecWeights: { I: 15 } },
                ],
            },
        ],

        conventional: [
            {
                id: '12-c1',
                type: 'slider',
                category: 'deepdive',
                text: 'Do you prefer work that is structured, predictable, and organized?',
                minLabel: 'No, boring',
                maxLabel: 'Yes, safe',
                primaryRIASEC: 'C',
                riasecWeights: { C: 15 },
            },
            {
                id: '12-c2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which of these careers sounds good?',
                riasecWeights: {},
                options: [
                    { text: 'Chartered Accountant (CA)', riasecWeights: { C: 15, E: 5 } },
                    { text: 'Data Analyst / Statistician', riasecWeights: { C: 12, I: 8 } },
                    { text: 'Bank Manager', riasecWeights: { C: 12, E: 8 } },
                    { text: 'Civil Services (IAS/IPS)', riasecWeights: { E: 10, S: 10, C: 5 } },
                ],
            },
            {
                id: '12-c3',
                type: 'scenario',
                category: 'deepdive',
                text: 'You find a mistake in a document. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'fix',
                        icon: '✅',
                        title: 'Fix Immediately',
                        description: 'Correct it so everything is perfect and accurate',
                        riasecWeights: { C: 15 },
                    },
                    {
                        id: 'ignore',
                        icon: '🤷',
                        title: 'Ignore if Minor',
                        description: 'If the meaning is clear, it doesn\'t matter much',
                        riasecWeights: { C: 0 },
                    },
                ],
            },
            {
                id: '12-c4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You are good at...',
                riasecWeights: {},
                options: [
                    { text: 'Managing money and budgets', riasecWeights: { C: 10, E: 5 } },
                    { text: 'Organizing events or schedules', riasecWeights: { C: 10 } },
                    { text: 'Working with spreadsheets (Excel)', riasecWeights: { C: 10, I: 3 } },
                    { text: 'Following complex rules', riasecWeights: { C: 10 } },
                ],
            },
            {
                id: '12-c5',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you value job security and stability?',
                minLabel: 'Not much',
                maxLabel: 'Very much',
                primaryRIASEC: 'C',
                riasecWeights: { C: 15 },
            },
            {
                id: '12-c6',
                type: 'scenario',
                category: 'deepdive',
                text: 'Your desk is...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'tidy',
                        icon: '🧹',
                        title: 'Always Tidy',
                        description: 'Everything has its place',
                        riasecWeights: { C: 15 },
                    },
                    {
                        id: 'messy',
                        icon: '🌪️',
                        title: 'Organized Chaos',
                        description: 'I know where everything is, but it looks messy',
                        riasecWeights: { C: 0, A: 5 },
                    },
                ],
            },
        ],
    },

    // NEW MODULES
    skills: [
        {
            id: '12-skill-1',
            type: 'slider-grid',
            category: 'baseline',
            text: 'Rate your proficiency in these subjects:',
            riasecWeights: {},
            skills: [
                { name: 'Mathematics', riasec: 'I' },
                { name: 'Physics', riasec: 'I' },
                { name: 'Chemistry', riasec: 'I' },
                { name: 'Biology', riasec: 'I' },
                { name: 'Computer Science', riasec: 'R' },
                { name: 'English', riasec: 'A' },
            ],
        },
        {
            id: '12-skill-2',
            type: 'checkbox-multi',
            category: 'baseline',
            text: 'Which of these soft skills are your strengths?',
            riasecWeights: {},
            options: [
                { text: 'Leadership', riasecWeights: { E: 5 } },
                { text: 'Communication', riasecWeights: { E: 3, S: 3 } },
                { text: 'Problem Solving', riasecWeights: { I: 5 } },
                { text: 'Creativity', riasecWeights: { A: 5 } },
                { text: 'Teamwork', riasecWeights: { S: 5 } },
                { text: 'Time Management', riasecWeights: { C: 5 } },
            ],
        },
    ],

    values: [
        {
            id: '12-val-1',
            type: 'ranking',
            category: 'baseline',
            text: 'What are your top priorities for your future lifestyle?',
            riasecWeights: {},
            options: [
                'Financial Freedom',
                'Helping Society',
                'Work-Life Balance',
                'Travel & Adventure',
                'Leadership & Power',
            ],
        },
        {
            id: '12-val-2',
            type: 'multiple-choice',
            category: 'baseline',
            text: 'Where do you see yourself in 10 years?',
            riasecWeights: {},
            options: [
                { text: 'Leading a large company', riasecWeights: { E: 10 } },
                { text: 'Making a breakthrough discovery', riasecWeights: { I: 10 } },
                { text: 'Creating art or entertainment', riasecWeights: { A: 10 } },
                { text: 'Running a non-profit organization', riasecWeights: { S: 10 } },
            ],
        },
    ],

    preferences: [
        {
            id: '12-pref-1',
            type: 'multiple-choice',
            category: 'baseline',
            text: 'Ideally, where would you like to work?',
            riasecWeights: {},
            options: [
                { text: 'In a modern office or corporate setting', riasecWeights: { E: 3, C: 3 } },
                { text: 'Outdoors, in nature or on-site', riasecWeights: { R: 5 } },
                { text: 'In a laboratory or research facility', riasecWeights: { I: 5 } },
                { text: 'In a creative studio or workshop', riasecWeights: { A: 5 } },
                { text: 'In a hospital or clinic', riasecWeights: { S: 3, I: 3 } },
            ],
        },
        {
            id: '12-pref-2',
            type: 'slider',
            category: 'baseline',
            text: 'How many years are you willing to study before starting your first job?',
            minLabel: 'As few as possible',
            maxLabel: 'As long as needed (5+ years)',
            primaryRIASEC: 'I',
            riasecWeights: { I: 5 },
        },
        {
            id: '12-pref-3',
            type: 'scenario',
            category: 'baseline',
            text: 'Do you prefer working alone or in a large team?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'solo',
                    icon: '👤',
                    title: 'Solo / Small Team',
                    description: 'I focus better when I work alone or with 1-2 others',
                    riasecWeights: { I: 5, R: 3, A: 3 },
                },
                {
                    id: 'team',
                    icon: '👥',
                    title: 'Large Team',
                    description: 'I enjoy the energy and collaboration of a big group',
                    riasecWeights: { E: 5, S: 5 },
                },
            ],
        },
    ],
};
