import type { QuestionBank } from './riasec-scoring';

export const questionBankFor10th: QuestionBank = {
    // BASELINE QUESTIONS (Asked to all students)
    baseline: [
        {
            id: '10-b1',
            type: 'scenario',
            category: 'baseline',
            text: 'You have a free weekend. How do you choose to spend it?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'r',
                    icon: '🛠️',
                    title: 'Build & Fix',
                    description: 'Repairing a cycle, building a model, or gardening',
                    riasecWeights: { R: 12 },
                },
                {
                    id: 'i',
                    icon: '🔭',
                    title: 'Explore & Analyze',
                    description: 'Watching a documentary, solving puzzles, or reading science news',
                    riasecWeights: { I: 12 },
                },
                {
                    id: 'a',
                    icon: '🎨',
                    title: 'Create & Express',
                    description: 'Sketching, playing music, or writing a story',
                    riasecWeights: { A: 12 },
                },
                {
                    id: 's',
                    icon: '👥',
                    title: 'Connect & Help',
                    description: 'Hanging out with friends or volunteering for a cause',
                    riasecWeights: { S: 12 },
                },
            ],
        },
        {
            id: '10-b2',
            type: 'scenario',
            category: 'baseline',
            text: 'Your school is organizing a fest. Which team do you join?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'e',
                    icon: '📢',
                    title: 'Marketing & Leadership',
                    description: 'Promoting the event and leading a team of volunteers',
                    riasecWeights: { E: 12 },
                },
                {
                    id: 'c',
                    icon: '📋',
                    title: 'Planning & Logistics',
                    description: 'Managing the schedule, budget, and supplies',
                    riasecWeights: { C: 12 },
                },
                {
                    id: 'r',
                    icon: '🏗️',
                    title: 'Stage & Setup',
                    description: 'Setting up the stage, lights, and sound system',
                    riasecWeights: { R: 12 },
                },
                {
                    id: 'a',
                    icon: '🎭',
                    title: 'Decoration & Design',
                    description: 'Designing posters and decorating the venue',
                    riasecWeights: { A: 12 },
                },
            ],
        },
        {
            id: '10-b3',
            type: 'scenario',
            category: 'baseline',
            text: 'Which school subject do you find most naturally interesting?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'i',
                    icon: '⚗️',
                    title: 'Science & Math',
                    description: 'Understanding how the world works through logic and experiments',
                    riasecWeights: { I: 12, R: 5 },
                },
                {
                    id: 's',
                    icon: '📚',
                    title: 'Social Studies',
                    description: 'Learning about history, society, and people',
                    riasecWeights: { S: 10, E: 5 },
                },
                {
                    id: 'a',
                    icon: '📝',
                    title: 'Languages & Arts',
                    description: 'Reading literature and expressing ideas creatively',
                    riasecWeights: { A: 12 },
                },
                {
                    id: 'c',
                    icon: '💻',
                    title: 'Computer Applications',
                    description: 'Working with software, data, and organized systems',
                    riasecWeights: { C: 10, I: 5 },
                },
            ],
        },
        {
            id: '10-b4',
            type: 'scenario',
            category: 'baseline',
            text: 'When solving a problem, what is your first instinct?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'i',
                    icon: '🧠',
                    title: 'Analyze It',
                    description: 'Research facts and think through the logic deeply',
                    riasecWeights: { I: 12 },
                },
                {
                    id: 'r',
                    icon: '🔧',
                    title: 'Act on It',
                    description: 'Try a practical solution immediately and see if it works',
                    riasecWeights: { R: 12 },
                },
                {
                    id: 's',
                    icon: '🗣️',
                    title: 'Discuss It',
                    description: 'Talk to others to get advice and different perspectives',
                    riasecWeights: { S: 12 },
                },
                {
                    id: 'e',
                    icon: '🚀',
                    title: 'Lead the Solution',
                    description: 'Take charge and direct others on what to do',
                    riasecWeights: { E: 12 },
                },
            ],
        },
        {
            id: '10-b5',
            type: 'scenario',
            category: 'baseline',
            text: 'Which TV show or YouTube channel genre do you prefer?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'i',
                    icon: '🌍',
                    title: 'Discovery & Tech',
                    description: 'Science, technology, space, or nature documentaries',
                    riasecWeights: { I: 10, R: 5 },
                },
                {
                    id: 'a',
                    icon: '🎬',
                    title: 'Movies & Art',
                    description: 'Films, animation, music, or creative DIYs',
                    riasecWeights: { A: 12 },
                },
                {
                    id: 'e',
                    icon: '🦈',
                    title: 'Business & Reality',
                    description: 'Shark Tank, entrepreneurship stories, or competitions',
                    riasecWeights: { E: 12 },
                },
                {
                    id: 's',
                    icon: '🎤',
                    title: 'Talk Shows & Vlogs',
                    description: 'Interviews, lifestyle vlogs, or social issues',
                    riasecWeights: { S: 12 },
                },
            ],
        },
    ],

    // DEEP-DIVE QUESTIONS
    deepdive: {
        realistic: [
            {
                id: '10-r1',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you enjoy working with your hands (repairing, building, crafting)?',
                minLabel: 'Avoid it',
                maxLabel: 'Love it',
                primaryRIASEC: 'R',
                riasecWeights: { R: 15 },
            },
            {
                id: '10-r2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which tool or equipment would you like to master?',
                riasecWeights: {},
                options: [
                    { text: '3D Printer or Laser Cutter', riasecWeights: { R: 12, I: 5 } },
                    { text: 'Power Tools (Drill, Saw)', riasecWeights: { R: 15 } },
                    { text: 'Computer Hardware Components', riasecWeights: { R: 10, I: 5 } },
                    { text: 'None of these', riasecWeights: { R: 0 } },
                ],
            },
            {
                id: '10-r3',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'Which of these have you done and enjoyed?',
                riasecWeights: {},
                options: [
                    { text: 'Fixed a broken appliance', riasecWeights: { R: 5 } },
                    { text: 'Built a working model for science fair', riasecWeights: { R: 5, I: 2 } },
                    { text: 'Gardening or farming', riasecWeights: { R: 5 } },
                    { text: 'Assembled furniture or a PC', riasecWeights: { R: 5 } },
                ],
            },
            {
                id: '10-r4',
                type: 'scenario',
                category: 'deepdive',
                text: 'A gadget at home stops working. What do you do?',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'fix',
                        icon: '🪛',
                        title: 'Open it up',
                        description: 'Unscrew it to see if I can fix the loose wire myself',
                        riasecWeights: { R: 15 },
                    },
                    {
                        id: 'call',
                        icon: '📞',
                        title: 'Call Support',
                        description: 'Look for the manual or call a technician',
                        riasecWeights: { R: 2, C: 5 },
                    },
                ],
            },
            {
                id: '10-r5',
                type: 'slider',
                category: 'deepdive',
                text: 'How comfortable are you with physical labor or outdoor work?',
                minLabel: 'Uncomfortable',
                maxLabel: 'Very Comfortable',
                primaryRIASEC: 'R',
                riasecWeights: { R: 15 },
            },
            {
                id: '10-r6',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'If you could build something right now, what would it be?',
                riasecWeights: {},
                options: [
                    { text: 'A robot or drone', riasecWeights: { R: 15, I: 5 } },
                    { text: 'A wooden table or chair', riasecWeights: { R: 15 } },
                    { text: 'A customized bicycle', riasecWeights: { R: 15 } },
                    { text: 'I prefer not to build things', riasecWeights: { R: 0 } },
                ],
            },
        ],

        investigative: [
            {
                id: '10-i1',
                type: 'slider',
                category: 'deepdive',
                text: 'How curious are you about the "Why" and "How" behind things?',
                minLabel: 'Not really',
                maxLabel: 'Very curious',
                primaryRIASEC: 'I',
                riasecWeights: { I: 15 },
            },
            {
                id: '10-i2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which topic would you read a book about?',
                riasecWeights: {},
                options: [
                    { text: 'The Mysteries of the Universe (Space)', riasecWeights: { I: 15 } },
                    { text: 'How the Human Brain Works', riasecWeights: { I: 12, S: 3 } },
                    { text: 'The History of Ancient Civilizations', riasecWeights: { I: 10, S: 5 } },
                    { text: 'Fiction or Fantasy', riasecWeights: { A: 5 } },
                ],
            },
            {
                id: '10-i3',
                type: 'slider-grid',
                category: 'deepdive',
                text: 'Rate your interest in these subjects:',
                riasecWeights: {},
                skills: [
                    { name: 'Physics', riasec: 'I' },
                    { name: 'Chemistry', riasec: 'I' },
                    { name: 'Biology', riasec: 'I' },
                    { name: 'Mathematics', riasec: 'I' },
                ],
            },
            {
                id: '10-i4',
                type: 'scenario',
                category: 'deepdive',
                text: 'You see a complex chart in a newspaper. Do you...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'analyze',
                        icon: '📊',
                        title: 'Analyze It',
                        description: 'Study it to understand the trends and data points',
                        riasecWeights: { I: 15 },
                    },
                    {
                        id: 'skip',
                        icon: '⏭️',
                        title: 'Skip It',
                        description: 'Glance over it and read the headlines instead',
                        riasecWeights: { I: 0 },
                    },
                ],
            },
            {
                id: '10-i5',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You enjoy activities that involve...',
                riasecWeights: {},
                options: [
                    { text: 'Solving riddles or logic puzzles', riasecWeights: { I: 10 } },
                    { text: 'Conducting science experiments', riasecWeights: { I: 15 } },
                    { text: 'Debating ideas and theories', riasecWeights: { I: 10, E: 5 } },
                    { text: 'Researching topics online', riasecWeights: { I: 10 } },
                ],
            },
            {
                id: '10-i6',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you like math and solving equations?',
                minLabel: 'Hate it',
                maxLabel: 'Love it',
                primaryRIASEC: 'I',
                riasecWeights: { I: 15 },
            },
        ],

        artistic: [
            {
                id: '10-a1',
                type: 'slider',
                category: 'deepdive',
                text: 'How important is it for you to be original and creative?',
                minLabel: 'Not important',
                maxLabel: 'Essential',
                primaryRIASEC: 'A',
                riasecWeights: { A: 15 },
            },
            {
                id: '10-a2',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'Which creative activities do you do in your free time?',
                riasecWeights: {},
                options: [
                    { text: 'Drawing, Painting, or Sketching', riasecWeights: { A: 5 } },
                    { text: 'Writing stories or poems', riasecWeights: { A: 5 } },
                    { text: 'Photography or Video Editing', riasecWeights: { A: 5, R: 2 } },
                    { text: 'Playing a musical instrument', riasecWeights: { A: 5 } },
                ],
            },
            {
                id: '10-a3',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'If you could design something, what would it be?',
                riasecWeights: {},
                options: [
                    { text: 'A new fashion line or outfit', riasecWeights: { A: 12 } },
                    { text: 'A futuristic building', riasecWeights: { A: 10, I: 5, R: 5 } },
                    { text: 'A video game character', riasecWeights: { A: 12, R: 2 } },
                    { text: 'A poster for a social cause', riasecWeights: { A: 10, S: 5 } },
                ],
            },
            {
                id: '10-a4',
                type: 'scenario',
                category: 'deepdive',
                text: 'You have to submit a project. How do you make it stand out?',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'visuals',
                        icon: '✨',
                        title: 'Unique Visuals',
                        description: 'Focus on beautiful design, colors, and presentation',
                        riasecWeights: { A: 15 },
                    },
                    {
                        id: 'content',
                        icon: '📄',
                        title: 'Solid Content',
                        description: 'Focus on accurate facts and clear structure',
                        riasecWeights: { C: 10, I: 5 },
                    },
                ],
            },
            {
                id: '10-a5',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you enjoy performing (acting, dancing, singing) in front of others?',
                minLabel: 'Terrified',
                maxLabel: 'Love the spotlight',
                primaryRIASEC: 'A',
                riasecWeights: { A: 15, E: 5 },
            },
            {
                id: '10-a6',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which career sounds most appealing?',
                riasecWeights: {},
                options: [
                    { text: 'Graphic Designer', riasecWeights: { A: 15 } },
                    { text: 'Writer / Author', riasecWeights: { A: 15 } },
                    { text: 'Actor / Musician', riasecWeights: { A: 15 } },
                    { text: 'None of these', riasecWeights: { A: 0 } },
                ],
            },
        ],

        social: [
            {
                id: '10-s1',
                type: 'slider',
                category: 'deepdive',
                text: 'How much satisfaction do you get from helping someone solve a personal problem?',
                minLabel: 'None',
                maxLabel: 'A lot',
                primaryRIASEC: 'S',
                riasecWeights: { S: 15 },
            },
            {
                id: '10-s2',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which volunteer role would you choose?',
                riasecWeights: {},
                options: [
                    { text: 'Teaching underprivileged kids', riasecWeights: { S: 15 } },
                    { text: 'Organizing a donation drive', riasecWeights: { S: 10, E: 5 } },
                    { text: 'Taking care of sick animals', riasecWeights: { S: 12, R: 3 } },
                    { text: 'Creating awareness posters', riasecWeights: { S: 8, A: 7 } },
                ],
            },
            {
                id: '10-s3',
                type: 'scenario',
                category: 'deepdive',
                text: 'A new student joins your class and looks lonely. Do you...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'talk',
                        icon: '👋',
                        title: 'Talk to them',
                        description: 'Go over, introduce yourself, and make them feel welcome',
                        riasecWeights: { S: 15 },
                    },
                    {
                        id: 'wait',
                        icon: '👀',
                        title: 'Wait & See',
                        description: 'Wait for them to approach you or someone else',
                        riasecWeights: { S: 0 },
                    },
                ],
            },
            {
                id: '10-s4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'People often come to you for...',
                riasecWeights: {},
                options: [
                    { text: 'Advice on personal issues', riasecWeights: { S: 5 } },
                    { text: 'Help with homework', riasecWeights: { S: 3, I: 2 } },
                    { text: 'Cheering up when they are sad', riasecWeights: { S: 5 } },
                    { text: 'Resolving fights between friends', riasecWeights: { S: 5, E: 2 } },
                ],
            },
            {
                id: '10-s5',
                type: 'slider',
                category: 'deepdive',
                text: 'How patient are you when explaining things to others?',
                minLabel: 'Impatient',
                maxLabel: 'Very Patient',
                primaryRIASEC: 'S',
                riasecWeights: { S: 15 },
            },
            {
                id: '10-s6',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'You prefer working...',
                riasecWeights: {},
                options: [
                    { text: 'In a team with lots of interaction', riasecWeights: { S: 15, E: 5 } },
                    { text: 'Alone or with one other person', riasecWeights: { I: 5, R: 5 } },
                    { text: 'Leading the group', riasecWeights: { E: 15, S: 5 } },
                    { text: 'It depends on the task', riasecWeights: {} },
                ],
            },
        ],

        enterprising: [
            {
                id: '10-e1',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you enjoy being the leader of a group?',
                minLabel: 'Prefer following',
                maxLabel: 'Love leading',
                primaryRIASEC: 'E',
                riasecWeights: { E: 15 },
            },
            {
                id: '10-e2',
                type: 'scenario',
                category: 'deepdive',
                text: 'Your team is losing a game. What do you do?',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'motivate',
                        icon: '🔥',
                        title: 'Motivate Team',
                        description: 'Give a pep talk and strategize to win',
                        riasecWeights: { E: 15 },
                    },
                    {
                        id: 'play',
                        icon: '🏃',
                        title: 'Just Play',
                        description: 'Focus on your own game and try your best',
                        riasecWeights: { R: 5 },
                    },
                ],
            },
            {
                id: '10-e3',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which school activity appeals to you?',
                riasecWeights: {},
                options: [
                    { text: 'Debate Team or Model UN', riasecWeights: { E: 12, S: 3 } },
                    { text: 'Student Council / Head Boy/Girl', riasecWeights: { E: 15 } },
                    { text: 'Organizing the School Fest', riasecWeights: { E: 12, C: 3 } },
                    { text: 'Science Club', riasecWeights: { I: 10 } },
                ],
            },
            {
                id: '10-e4',
                type: 'slider-grid',
                category: 'deepdive',
                text: 'Rate your confidence in these skills:',
                riasecWeights: {},
                skills: [
                    { name: 'Public Speaking', riasec: 'E' },
                    { name: 'Persuading Others', riasec: 'E' },
                    { name: 'Selling an Idea', riasec: 'E' },
                    { name: 'Making Decisions', riasec: 'E' },
                ],
            },
            {
                id: '10-e5',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You would like a job where you...',
                riasecWeights: {},
                options: [
                    { text: 'Make important decisions', riasecWeights: { E: 10 } },
                    { text: 'Start your own business', riasecWeights: { E: 15 } },
                    { text: 'Manage other people', riasecWeights: { E: 10, S: 5 } },
                    { text: 'Compete to be the best', riasecWeights: { E: 10 } },
                ],
            },
            {
                id: '10-e6',
                type: 'scenario',
                category: 'deepdive',
                text: 'You need to raise money for a class trip. You...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'sell',
                        icon: '💰',
                        title: 'Organize a Sale',
                        description: 'Set up a stall and sell cookies or crafts',
                        riasecWeights: { E: 15 },
                    },
                    {
                        id: 'ask',
                        icon: '📝',
                        title: 'Write a Letter',
                        description: 'Write a formal request to the principal or parents',
                        riasecWeights: { C: 10, S: 5 },
                    },
                ],
            },
        ],

        conventional: [
            {
                id: '10-c1',
                type: 'slider',
                category: 'deepdive',
                text: 'Do you like having a clear routine and organized schedule?',
                minLabel: 'Hate routine',
                maxLabel: 'Need routine',
                primaryRIASEC: 'C',
                riasecWeights: { C: 15 },
            },
            {
                id: '10-c2',
                type: 'scenario',
                category: 'deepdive',
                text: 'You are taking notes in class. Your notebook is...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'neat',
                        icon: '📝',
                        title: 'Neat & Structured',
                        description: 'Organized with headings, bullet points, and highlighters',
                        riasecWeights: { C: 15 },
                    },
                    {
                        id: 'messy',
                        icon: '✍️',
                        title: 'Rough & Quick',
                        description: 'Just scribbles to capture the main points',
                        riasecWeights: { C: 0 },
                    },
                ],
            },
            {
                id: '10-c3',
                type: 'multiple-choice',
                category: 'deepdive',
                text: 'Which task would you prefer in a group project?',
                riasecWeights: {},
                options: [
                    { text: 'Proofreading and formatting the report', riasecWeights: { C: 15 } },
                    { text: 'Managing the budget and expenses', riasecWeights: { C: 12, E: 3 } },
                    { text: 'Creating the presentation slides', riasecWeights: { A: 8, C: 5 } },
                    { text: 'Doing the research', riasecWeights: { I: 10 } },
                ],
            },
            {
                id: '10-c4',
                type: 'checkbox-multi',
                category: 'deepdive',
                text: 'You are good at...',
                riasecWeights: {},
                options: [
                    { text: 'Keeping your room tidy', riasecWeights: { C: 5 } },
                    { text: 'Remembering dates and details', riasecWeights: { C: 5 } },
                    { text: 'Following instructions precisely', riasecWeights: { C: 5 } },
                    { text: 'Spotting spelling mistakes', riasecWeights: { C: 5 } },
                ],
            },
            {
                id: '10-c5',
                type: 'slider',
                category: 'deepdive',
                text: 'How much do you enjoy working with data, numbers, and lists?',
                minLabel: 'Boring',
                maxLabel: 'Satisfying',
                primaryRIASEC: 'C',
                riasecWeights: { C: 15 },
            },
            {
                id: '10-c6',
                type: 'scenario',
                category: 'deepdive',
                text: 'You are playing a board game. You are the one who...',
                riasecWeights: {},
                scenarios: [
                    {
                        id: 'rules',
                        icon: '📜',
                        title: 'Reads the Rules',
                        description: 'Makes sure everyone follows the rules correctly',
                        riasecWeights: { C: 15 },
                    },
                    {
                        id: 'fun',
                        icon: '🎲',
                        title: 'Just Plays',
                        description: 'Doesn\'t care much about rules, just wants to have fun',
                        riasecWeights: { S: 5 },
                    },
                ],
            },
        ],
    },

    // NEW MODULES
    academic: [
        {
            id: '10-acad-1',
            type: 'checkbox-multi',
            category: 'baseline',
            text: 'Which subjects do you consistently score highest in?',
            riasecWeights: {},
            options: [
                { text: 'Mathematics', academic: 'math', riasecWeights: { I: 5, C: 3 } },
                { text: 'Science', academic: 'science', riasecWeights: { I: 5, R: 3 } },
                { text: 'English / Languages', academic: 'language', riasecWeights: { A: 3, S: 3 } },
                { text: 'Social Studies', academic: 'social', riasecWeights: { S: 3, I: 2 } },
                { text: 'Computer Science', academic: 'cs', riasecWeights: { I: 3, R: 3, C: 3 } },
            ],
        },
        {
            id: '10-acad-2',
            type: 'slider',
            category: 'baseline',
            text: 'How much effort do you need to put in to understand Math concepts?',
            minLabel: 'Very Hard',
            maxLabel: 'Easy / Natural',
            primaryRIASEC: 'I',
            riasecWeights: { I: 5, C: 3 },
        },
        {
            id: '10-acad-3',
            type: 'slider',
            category: 'baseline',
            text: 'How much do you enjoy writing essays or stories?',
            minLabel: 'Hate it',
            maxLabel: 'Love it',
            primaryRIASEC: 'A',
            riasecWeights: { A: 5 },
        },
    ],

    values: [
        {
            id: '10-val-1',
            type: 'ranking',
            category: 'baseline',
            text: 'Rank these based on what matters most to you for a future job:',
            riasecWeights: {},
            options: [
                'Making a lot of money',
                'Helping other people',
                'Being famous or recognized',
                'Having a stable, secure life',
                'Being creative and original',
            ],
        },
        {
            id: '10-val-2',
            type: 'multiple-choice',
            category: 'baseline',
            text: 'What is your definition of success?',
            riasecWeights: {},
            options: [
                { text: 'Being rich and powerful', riasecWeights: { E: 5 } },
                { text: 'Making a difference in the world', riasecWeights: { S: 5 } },
                { text: 'Discovering something new', riasecWeights: { I: 5 } },
                { text: 'Creating something beautiful', riasecWeights: { A: 5 } },
            ],
        },
    ],

    learningStyle: [
        {
            id: '10-ls-1',
            type: 'multiple-choice',
            category: 'baseline',
            text: 'How do you learn best?',
            riasecWeights: {},
            options: [
                { text: 'Watching videos or demonstrations (Visual)', learningStyle: 'visual', riasecWeights: {} },
                { text: 'Listening to the teacher explain (Auditory)', learningStyle: 'auditory', riasecWeights: {} },
                { text: 'Doing it yourself / Hands-on (Kinesthetic)', learningStyle: 'kinesthetic', riasecWeights: { R: 3 } },
                { text: 'Reading the textbook (Read/Write)', learningStyle: 'reading', riasecWeights: { I: 2, C: 2 } },
            ],
        },
        {
            id: '10-ls-2',
            type: 'scenario',
            category: 'baseline',
            text: 'You have to learn a new game. You...',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'play',
                    icon: '🎮',
                    title: 'Start Playing',
                    description: 'Learn as you go (Trial & Error)',
                    riasecWeights: { R: 5 },
                },
                {
                    id: 'watch',
                    icon: '👀',
                    title: 'Watch Others',
                    description: 'Observe someone else play first',
                    riasecWeights: { S: 2 },
                },
            ],
        },
    ],

    preferences: [
        {
            id: '10-pref-1',
            type: 'multiple-choice',
            category: 'baseline',
            text: 'Ideally, where would you like to work?',
            riasecWeights: {},
            options: [
                { text: 'In a modern office or corporate setting', riasecWeights: { E: 3, C: 3 } },
                { text: 'Outdoors, in nature or on-site', riasecWeights: { R: 5 } },
                { text: 'In a laboratory or research facility', riasecWeights: { I: 5 } },
                { text: 'In a creative studio or workshop', riasecWeights: { A: 5 } },
                { text: 'In a hospital or clinic', riasecWeights: { S: 3, I: 3 } },
            ],
        },
        {
            id: '10-pref-2',
            type: 'slider',
            category: 'baseline',
            text: 'How many years are you willing to study before starting your first job?',
            minLabel: 'As few as possible',
            maxLabel: 'As long as needed (5+ years)',
            primaryRIASEC: 'I',
            riasecWeights: { I: 5 },
        },
        {
            id: '10-pref-3',
            type: 'scenario',
            category: 'baseline',
            text: 'Do you prefer working alone or in a large team?',
            riasecWeights: {},
            scenarios: [
                {
                    id: 'solo',
                    icon: '👤',
                    title: 'Solo / Small Team',
                    description: 'I focus better when I work alone or with 1-2 others',
                    riasecWeights: { I: 5, R: 3, A: 3 },
                },
                {
                    id: 'team',
                    icon: '👥',
                    title: 'Large Team',
                    description: 'I enjoy the energy and collaboration of a big group',
                    riasecWeights: { E: 5, S: 5 },
                },
            ],
        },
    ],
};
